drop view `dim_ads_industry_account_df_view_test`;
CREATE VIEW `dim_ads_industry_account_df_view_test` (brand_account_id
  ,brand_user_name
  ,company_code
  ,company_name
  ,group_code
  ,group_name
  ,trade_type_first_name
  ,trade_type_second_name
  ,track_group_id
  ,track_group_name
  ,active_level
  ,cpc_direct_sales_code
  ,cpc_direct_sales_name
  ,cpc_direct_sales_dept1_code
  ,cpc_direct_sales_dept1_name
  ,cpc_direct_sales_dept2_code
  ,cpc_direct_sales_dept2_name
  ,cpc_direct_sales_dept3_code
  ,cpc_direct_sales_dept3_name
  ,cpc_direct_sales_dept4_code
  ,cpc_direct_sales_dept4_name
  ,cpc_direct_sales_dept5_code
  ,cpc_direct_sales_dept5_name
  ,cpc_direct_sales_dept6_code
  ,cpc_direct_sales_dept6_name
  ,brand_direct_sales_code
  ,brand_direct_sales_name
  ,brand_direct_sales_dept1_code
  ,brand_direct_sales_dept1_name
  ,brand_direct_sales_dept2_code
  ,brand_direct_sales_dept2_name
  ,brand_direct_sales_dept3_code
  ,brand_direct_sales_dept3_name
  ,brand_direct_sales_dept4_code
  ,brand_direct_sales_dept4_name
  ,brand_direct_sales_dept5_code
  ,brand_direct_sales_dept5_name
  ,brand_direct_sales_dept6_code
  ,brand_direct_sales_dept6_name
  ,chips_direct_operator_code
  ,chips_direct_operator_name
  ,chips_direct_operator_dept1_code
  ,chips_direct_operator_dept1_name
  ,chips_direct_operator_dept2_code
  ,chips_direct_operator_dept2_name
  ,chips_direct_operator_dept3_code
  ,chips_direct_operator_dept3_name
  ,chips_direct_operator_dept4_code
  ,chips_direct_operator_dept4_name
  ,chips_direct_operator_dept5_code
  ,chips_direct_operator_dept5_name
  ,chips_direct_operator_dept6_code
  ,chips_direct_operator_dept6_name
  ,bcoo_direct_sales_code
  ,bcoo_direct_sales_name
  ,bcoo_direct_sales_dept1_code
  ,bcoo_direct_sales_dept1_name
  ,bcoo_direct_sales_dept2_code
  ,bcoo_direct_sales_dept2_name
  ,bcoo_direct_sales_dept3_code
  ,bcoo_direct_sales_dept3_name
  ,bcoo_direct_sales_dept4_code
  ,bcoo_direct_sales_dept4_name
  ,bcoo_direct_sales_dept5_code
  ,bcoo_direct_sales_dept5_name
  ,bcoo_direct_sales_dept6_code
  ,bcoo_direct_sales_dept6_name
  ,dtm
  ,brand_tag_code
  ,brand_tag_name
  ,brand_group_tag_code
  ,brand_group_tag_name
  ,first_industry_name
  ,second_industry_name
  ,track_detail_name
  ,track_industry_name
  ,cpc_operator_code
  ,cpc_operator_name
  ,cpc_operator_dept1_code
  ,cpc_operator_dept1_name
  ,cpc_operator_dept2_code
  ,cpc_operator_dept2_name
  ,cpc_operator_dept3_code
  ,cpc_operator_dept3_name
  ,cpc_operator_dept4_code
  ,cpc_operator_dept4_name
  ,cpc_operator_dept5_code
  ,cpc_operator_dept5_name
  ,cpc_operator_dept6_code
  ,cpc_operator_dept6_name
  ,brand_active_level
  ,ads_last_cost_days
  ,bimonthly_last_brand_active_level
  ,ads_last_cost_date
  ,brand_account_create_time
  ,brand_account_create_date,
direct_sales_dept3_name,
direct_sales_dept4_all_name ,
direct_sales_dept5_all_name
  ) COMMENT "VIEW" AS select
a.brand_account_id
  ,brand_user_name
  ,company_code
  ,company_name
  ,group_code
  ,group_name
  ,trade_type_first_name
  ,trade_type_second_name
  ,track_group_id
  ,track_group_name
  ,active_level
  ,cpc_direct_sales_code
  ,cpc_direct_sales_name
  ,cpc_direct_sales_dept1_code
  ,cpc_direct_sales_dept1_name
  ,cpc_direct_sales_dept2_code
  ,cpc_direct_sales_dept2_name
  ,cpc_direct_sales_dept3_code
  ,cpc_direct_sales_dept3_name
  ,cpc_direct_sales_dept4_code
  ,cpc_direct_sales_dept4_name
  ,cpc_direct_sales_dept5_code
  ,cpc_direct_sales_dept5_name
  ,cpc_direct_sales_dept6_code
  ,cpc_direct_sales_dept6_name
  ,brand_direct_sales_code
  ,brand_direct_sales_name
  ,brand_direct_sales_dept1_code
  ,brand_direct_sales_dept1_name
  ,brand_direct_sales_dept2_code
  ,brand_direct_sales_dept2_name
  ,brand_direct_sales_dept3_code
  ,brand_direct_sales_dept3_name
  ,brand_direct_sales_dept4_code
  ,brand_direct_sales_dept4_name
  ,brand_direct_sales_dept5_code
  ,brand_direct_sales_dept5_name
  ,brand_direct_sales_dept6_code
  ,brand_direct_sales_dept6_name
  ,chips_direct_operator_code
  ,chips_direct_operator_name
  ,chips_direct_operator_dept1_code
  ,chips_direct_operator_dept1_name
  ,chips_direct_operator_dept2_code
  ,chips_direct_operator_dept2_name
  ,chips_direct_operator_dept3_code
  ,chips_direct_operator_dept3_name
  ,chips_direct_operator_dept4_code
  ,chips_direct_operator_dept4_name
  ,chips_direct_operator_dept5_code
  ,chips_direct_operator_dept5_name
  ,chips_direct_operator_dept6_code
  ,chips_direct_operator_dept6_name
  ,bcoo_direct_sales_code
  ,bcoo_direct_sales_name
  ,bcoo_direct_sales_dept1_code
  ,bcoo_direct_sales_dept1_name
  ,bcoo_direct_sales_dept2_code
  ,bcoo_direct_sales_dept2_name
  ,bcoo_direct_sales_dept3_code
  ,bcoo_direct_sales_dept3_name
  ,bcoo_direct_sales_dept4_code
  ,bcoo_direct_sales_dept4_name
  ,bcoo_direct_sales_dept5_code
  ,bcoo_direct_sales_dept5_name
  ,bcoo_direct_sales_dept6_code
  ,bcoo_direct_sales_dept6_name
  , a.dtm
  ,brand_tag_code
  ,brand_tag_name
  ,brand_group_tag_code
  ,brand_group_tag_name
  ,first_industry_name
  ,second_industry_name
  ,track_detail_name
  ,track_industry_name
  ,cpc_operator_code
  ,cpc_operator_name
  ,cpc_operator_dept1_code
  ,cpc_operator_dept1_name
  ,cpc_operator_dept2_code
  ,cpc_operator_dept2_name
  ,cpc_operator_dept3_code
  ,cpc_operator_dept3_name
  ,cpc_operator_dept4_code
  ,cpc_operator_dept4_name
  ,cpc_operator_dept5_code
  ,cpc_operator_dept5_name
  ,cpc_operator_dept6_code
  ,cpc_operator_dept6_name
  ,brand_active_level
  ,ads_last_cost_days
  ,bimonthly_last_brand_active_level
  ,ads_last_cost_date
  ,brand_account_create_time
  ,brand_account_create_date,
direct_sales_dept3_name,
direct_sales_dept4_all_name ,
direct_sales_dept5_all_name
FROM
  (SELECT `reddm`.`dim_ads_industry_account_df`.`brand_account_id`,
`reddm`.`dim_ads_industry_account_df`.`dtm`,
`reddm`.`dim_ads_industry_account_df`.`ads_last_cost_days`,
`reddm`.`dim_ads_industry_account_df`.`bimonthly_last_brand_active_level`,
`reddm`.`dim_ads_industry_account_df`.`brand_active_level`,
`reddm`.`dim_ads_industry_account_df`.`ads_last_cost_date`
FROM `reddm`.`dim_ads_industry_account_df`) a
  left join 
  (select brand_account_id
  ,brand_user_name
  ,company_code
  ,company_name
  ,group_code
  ,group_name
  ,trade_type_first_name
  ,trade_type_second_name
  ,track_group_id
  ,track_group_name
  ,active_level
  ,cpc_direct_sales_code
  ,cpc_direct_sales_name
  ,cpc_direct_sales_dept1_code
  ,cpc_direct_sales_dept1_name
  ,cpc_direct_sales_dept2_code
  ,cpc_direct_sales_dept2_name
  ,cpc_direct_sales_dept3_code
  ,cpc_direct_sales_dept3_name
  ,cpc_direct_sales_dept4_code
  ,cpc_direct_sales_dept4_name
  ,cpc_direct_sales_dept5_code
  ,cpc_direct_sales_dept5_name
  ,cpc_direct_sales_dept6_code
  ,cpc_direct_sales_dept6_name
  ,brand_direct_sales_code
  ,brand_direct_sales_name
  ,brand_direct_sales_dept1_code
  ,brand_direct_sales_dept1_name
  ,brand_direct_sales_dept2_code
  ,brand_direct_sales_dept2_name
  ,brand_direct_sales_dept3_code
  ,brand_direct_sales_dept3_name
  ,brand_direct_sales_dept4_code
  ,brand_direct_sales_dept4_name
  ,brand_direct_sales_dept5_code
  ,brand_direct_sales_dept5_name
  ,brand_direct_sales_dept6_code
  ,brand_direct_sales_dept6_name
  ,chips_direct_operator_code
  ,chips_direct_operator_name
  ,chips_direct_operator_dept1_code
  ,chips_direct_operator_dept1_name
  ,chips_direct_operator_dept2_code
  ,chips_direct_operator_dept2_name
  ,chips_direct_operator_dept3_code
  ,chips_direct_operator_dept3_name
  ,chips_direct_operator_dept4_code
  ,chips_direct_operator_dept4_name
  ,chips_direct_operator_dept5_code
  ,chips_direct_operator_dept5_name
  ,chips_direct_operator_dept6_code
  ,chips_direct_operator_dept6_name
  ,bcoo_direct_sales_code
  ,bcoo_direct_sales_name
  ,bcoo_direct_sales_dept1_code
  ,bcoo_direct_sales_dept1_name
  ,bcoo_direct_sales_dept2_code
  ,bcoo_direct_sales_dept2_name
  ,bcoo_direct_sales_dept3_code
  ,bcoo_direct_sales_dept3_name
  ,bcoo_direct_sales_dept4_code
  ,bcoo_direct_sales_dept4_name
  ,bcoo_direct_sales_dept5_code
  ,bcoo_direct_sales_dept5_name
  ,bcoo_direct_sales_dept6_code
  ,bcoo_direct_sales_dept6_name
  ,brand_tag_code
  ,brand_tag_name
  ,brand_group_tag_code
  ,brand_group_tag_name
  ,first_industry_name
  ,second_industry_name
  ,track_detail_name
  ,track_industry_name
  ,cpc_operator_code
  ,cpc_operator_name
  ,cpc_operator_dept1_code
  ,cpc_operator_dept1_name
  ,cpc_operator_dept2_code
  ,cpc_operator_dept2_name
  ,cpc_operator_dept3_code
  ,cpc_operator_dept3_name
  ,cpc_operator_dept4_code
  ,cpc_operator_dept4_name
  ,cpc_operator_dept5_code
  ,cpc_operator_dept5_name
  ,cpc_operator_dept6_code
  ,cpc_operator_dept6_name
  ,brand_account_create_time
  ,brand_account_create_date,
direct_sales_dept3_name,
direct_sales_dept4_all_name ,
direct_sales_dept5_all_name
    from `reddm`.`dim_ads_industry_account_df` 
    where (date(`reddm`.`dim_ads_industry_account_df`.`dtm`)) = (from_unixtime(((unix_timestamp(now())) - 86400) - 25200,
  '%Y-%m-%d'))
    )b 
  on a.brand_account_id = b.brand_account_id