--old_sql
SELECT t1.date_key,
t1.module,
product,
marketing_target,
t1.spu_id AS spu_id ,
t1.brand_id AS brand_id,
t1.brand_name AS brand_name,
t1.spu_name AS spu_name,
t1.commercial_taxonomy_name1,
t1.commercial_code2 ,
t1.commercial_taxonomy_name2,
t1.commercial_code3,
t1.commercial_taxonomy_name3,
t1.commercial_code4,
t1.commercial_taxonomy_name4 ,
t1.brand_account_id,
imp_num,
click_num,
like_num,
fav_num ,
read_feed_num,
share_num,
query_num,
note_screenshot_num,
ti_user_num ,
ti_level,
imp_note_num,
bind_note_num,
softad_imp_note_num,
pos_imp_note_num ,
new_note_num,
cash_cost,
bind_cash_cost,
imp_emotional_note_num,
brand_ti_user_num ,
direct_sales_dept1_name,
direct_sales_dept2_name ,
CASE  WHEN direct_sales_dept3_name = '美奢潮流服饰行业' THEN '美奢洗护行业' WHEN direct_sales_dept3_name = '生活服务行业' THEN '本地客户业务部' ELSE direct_sales_dept3_name END AS direct_sales_dept3_name,
direct_sales_dept4_name,
direct_sales_dept5_name,
direct_sales_dept6_name,
direct_sales_name ,
operator_name,
operator_code,
direct_sales_code,
brand_account_name,
first_industry_name ,
second_industry_name,
t1.dtm,
brand_group_tag_name,
cost_note_num,
bind_cost_note_num ,
bind_splash_creativity_num,
bind_splash_cash_cost,
cpc_operator_name,
channel_sales_name,
taobao_rgmv_1m ,
tianmao_rgmv_1m,
pic_url,
rgmv_1m AS rgmv,
channel_operator_name,
i_user_num ,
a_user_num,
s_user_num,
planner_name,
staff_name,
cost ,
bind_cost,
is_cspu,
jd_rgmv_1m,
dou_rgmv_1m FROM ( SELECT date_key,
  module,
product,
marketing_target,
spu_id ,
brand_id,
brand_name,
spu_name,
commercial_taxonomy_name1,
commercial_code2 ,
commercial_taxonomy_name2,
commercial_code3,
commercial_taxonomy_name3,
commercial_code4,
commercial_taxonomy_name4 ,
brand_account_id,
imp_num,
click_num,
like_num,
fav_num ,
read_feed_num,
share_num,
query_num,
note_screenshot_num,
ti_user_num ,
imp_note_num,
bind_note_num,
softad_imp_note_num,
pos_imp_note_num,
new_note_num ,
cash_cost,
bind_cash_cost,
imp_emotional_note_num,
brand_ti_user_num,
dtm ,
cost_note_num,
bind_cost_note_num,
bind_splash_creativity_num,
bind_splash_cash_cost,
channel_sales_name ,
pic_url,
rgmv,
channel_operator_name,
i_user_num,
a_user_num ,
s_user_num,
planner_name,
staff_name,
cost,
bind_cost ,
is_cspu FROM reddm.dm_ads_pub_spu_cvr_cost_1d_di ) t1 LEFT JOIN ( SELECT brand_account_id,
direct_sales_dept1_name,
direct_sales_dept2_name,
direct_sales_dept3_name,
direct_sales_dept4_name ,
direct_sales_dept5_name,
direct_sales_dept6_name,
direct_sales_name,
operator_name,
operator_code ,
direct_sales_code,
brand_user_name AS brand_account_name,
first_industry_name,
second_industry_name,
brand_group_tag_name ,
operator_name AS cpc_operator_name FROM redapp.app_ads_insight_industry_account_df WHERE dtm = ( SELECT max(dtm) FROM redapp.app_ads_insight_industry_account_df ) ) t2 ON t1.brand_account_id = t2.brand_account_id LEFT JOIN ( SELECT spu_id,
dtm,
ti_level FROM reddm.dm_ads_pub_spu_cvr_cost_1d_di WHERE module = '整体' GROUP BY spu_id,
dtm,
ti_level ) t3 ON t3.spu_id = t1.spu_id AND t3.dtm = t1.dtm LEFT JOIN ( SELECT stat_month,
spu_id,
coalesce(module,
  '整体') AS module ,
taobao_rgmv_1m,
tianmao_rgmv_1m,
jd_rgmv_1m,
dou_rgmv_1m,
rgmv_1m ,
date_key FROM redapp.app_ads_insight_ecm_spu_gmv_df WHERE dtm = ( SELECT max(dtm) FROM redapp.app_ads_insight_ecm_spu_gmv_df ) ) t4 ON t4.spu_id = t1.spu_id AND CAST(t4.date_key AS int) = t1.dtm AND t1.module = t4.module


select t1.date_key,
  t1.module,
  product,
  marketing_target,
  t1.spu_id as spu_id,
  t1.brand_id as brand_id,
  t1.brand_name as brand_name,
  t1.spu_name as spu_name,
  t1.commercial_taxonomy_name1,
  t1.commercial_code2,
  t1.commercial_taxonomy_name2,
  t1.commercial_code3,
  t1.commercial_taxonomy_name3,
  t1.commercial_code4,
  t1.commercial_taxonomy_name4,
  t1.brand_account_id,
  imp_num,
  click_num,
  like_num,
  fav_num,
  read_feed_num,
  share_num,
  query_num,
  note_screenshot_num,
  ti_user_num,
  ti_level,
  imp_note_num,
  bind_note_num,
  softad_imp_note_num,
  pos_imp_note_num,
  new_note_num,
  cash_cost,
  bind_cash_cost,
  imp_emotional_note_num,
  brand_ti_user_num,
  direct_sales_dept1_name,
    direct_sales_dept2_name,
    case when direct_sales_dept3_name = '美奢潮流服饰行业' then '美奢洗护行业' when direct_sales_dept3_name ='生活服务行业' then '本地客户业务部' else direct_sales_dept3_name end as direct_sales_dept3_name,
    direct_sales_dept4_name,
    direct_sales_dept5_name,
    direct_sales_dept6_name,
    direct_sales_name,
    operator_name,
    operator_code ,
    direct_sales_code,
    brand_account_name,
    first_industry_name,
    second_industry_name,
    t1.dtm,
    brand_group_tag_name,
    cost_note_num,
  bind_cost_note_num,
  bind_splash_creativity_num,
  bind_splash_cash_cost,
  cpc_operator_name,
  channel_sales_name,
  taobao_rgmv_1m,
  tianmao_rgmv_1m,
  pic_url,
  rgmv_1m as rgmv,
  channel_operator_name,
  i_user_num,
  a_user_num,
  s_user_num,
  planner_name,
  staff_name,
  cost,
  bind_cost,
  is_cspu,
  jd_rgmv_1m ,
  dou_rgmv_1m ,
  campaign_cnt,
  note_cnt,
  income_campaign_cnt,
  income_note_cnt,
  ads_imp_cnt,
  ads_click_cnt,
  ads_income_amt,
  click_rgmv_7d,
  total_purchase_order_num,
  ecm_income_amt,
  cost_special_campaign,
  min_campaign_budget,
  pgc_new_note_num,
  pgc_note_num_6m
from 
(select date_key,
  module,
  product,
  marketing_target,
  spu_id,
  brand_id,
  brand_name,
  spu_name,
  commercial_taxonomy_name1,
  commercial_code2,
  commercial_taxonomy_name2,
  commercial_code3,
  commercial_taxonomy_name3,
  commercial_code4,
  commercial_taxonomy_name4,
  brand_account_id,
  imp_num,
  click_num,
  like_num,
  fav_num,
  read_feed_num,
  share_num,
  query_num,
  note_screenshot_num,
  ti_user_num,
  ti_level,
  imp_note_num,
  bind_note_num,
  softad_imp_note_num,
  pos_imp_note_num,
  new_note_num,
  cash_cost,
  bind_cash_cost,
  imp_emotional_note_num,
  brand_ti_user_num,
  cast(replace(date_key,'-','') as int) as dtm,
  cost_note_num,
  bind_cost_note_num,
  bind_splash_creativity_num,
  bind_splash_cash_cost,
  channel_sales_name,
  pic_url,
  rgmv,
  channel_operator_name,
  i_user_num,
  a_user_num,
  s_user_num,
  planner_name,
  staff_name,
  cost,
  bind_cost,
  is_cspu,
  campaign_cnt,
  note_cnt,
  income_campaign_cnt,
  income_note_cnt,
  ads_imp_cnt,
  ads_click_cnt,
  ads_income_amt,
  click_rgmv_7d,
  total_purchase_order_num,
  ecm_income_amt,
  cost_special_campaign,
  min_campaign_budget,
  pgc_new_note_num,
  pgc_note_num_6m
from 
reddm.dm_ads_pub_spu_product_cvr_cost_td_df
where dtm=(select max(dtm) from reddm.dm_ads_pub_spu_product_cvr_cost_td_df )

)t1 
left join 
(select brand_account_id,
      direct_sales_dept1_name,
      direct_sales_dept2_name,
      direct_sales_dept3_name,
      direct_sales_dept4_name,
      direct_sales_dept5_name,
      direct_sales_dept6_name,
      direct_sales_name,
      operator_name,
      operator_code ,
      direct_sales_code,
      brand_user_name as brand_account_name,
      first_industry_name,
      second_industry_name,
      brand_group_tag_name,
      operator_name as cpc_operator_name
from redapp.app_ads_insight_industry_account_df
where dtm= (select max(dtm) from redapp.app_ads_insight_industry_account_df) 
)t2 
on t1.brand_account_id = t2.brand_account_id

left join 
(select stat_month,
  spu_id,
  coalesce(module,'整体') as module,
  taobao_rgmv_1m,
  tianmao_rgmv_1m,
  jd_rgmv_1m ,
  dou_rgmv_1m ,
  rgmv_1m,
  date_key
from redapp.app_ads_insight_ecm_spu_gmv_df
where dtm= (select max(dtm) from redapp.app_ads_insight_ecm_spu_gmv_df ) 
)t4
on t4.spu_id = t1.spu_id and cast(t4.date_key as int)= t1.dtm and t1.module = t4.module