select date_key,
  t1.module,
  product,
  marketing_target,
  t1.spu_id as spu_id,
  t1.brand_id as brand_id,
  t1.brand_name as brand_name,
  t1.spu_name as spu_name,
  t1.commercial_taxonomy_name1,
  t1.commercial_code2,
  t1.commercial_taxonomy_name2,
  t1.commercial_code3,
  t1.commercial_taxonomy_name3,
  t1.commercial_code4,
  t1.commercial_taxonomy_name4,
  t1.brand_account_id,
  imp_num,
  click_num,
  like_num,
  fav_num,
  read_feed_num,
  share_num,
  query_num,
  note_screenshot_num,
  ti_user_num,
  ti_level,
  imp_note_num,
  bind_note_num,
  softad_imp_note_num,
  pos_imp_note_num,
  new_note_num,
  cash_cost,
  bind_cash_cost,
  imp_emotional_note_num,
  brand_ti_user_num,
  direct_sales_dept1_name,
    direct_sales_dept2_name,
    case when direct_sales_dept3_name = '美奢潮流服饰行业' then '美奢洗护行业' when direct_sales_dept3_name ='生活服务行业' then '本地客户业务部' else direct_sales_dept3_name end as direct_sales_dept3_name,
    direct_sales_dept4_name,
    direct_sales_dept5_name,
    direct_sales_dept6_name,
    direct_sales_name,
    operator_name,
    operator_code ,
    direct_sales_code,
    brand_account_name,
    first_industry_name,
    second_industry_name,
    t1.dtm,
    brand_group_tag_name,
    cost_note_num,
  bind_cost_note_num,
  bind_splash_creativity_num,
  bind_splash_cash_cost,
  cpc_operator_name,
  channel_sales_name,
  case when tag='01' then taobao_rgmv_1m else 0 end as taobao_rgmv_1m,
  case when tag='01' then tianmao_rgmv_1m else 0 end as tianmao_rgmv_1m,
  pic_url,
  case when taobao_rgmv_1m>0 and tianmao_rgmv_1m>0 then rgmv else 0 end as rgmv

from 
(select date_key,
  module,
  product,
  marketing_target,
  spu_id,
  brand_id,
  brand_name,
  spu_name,
  commercial_taxonomy_name1,
  commercial_code2,
  commercial_taxonomy_name2,
  commercial_code3,
  commercial_taxonomy_name3,
  commercial_code4,
  commercial_taxonomy_name4,
  brand_account_id,
  imp_num,
  click_num,
  like_num,
  fav_num,
  read_feed_num,
  share_num,
  query_num,
  note_screenshot_num,
  ti_user_num,
  --ti_level,
  imp_note_num,
  bind_note_num,
  softad_imp_note_num,
  pos_imp_note_num,
  new_note_num,
  cash_cost,
  bind_cash_cost,
  imp_emotional_note_num,
  brand_ti_user_num,
  dtm,
  cost_note_num,
  bind_cost_note_num,
  bind_splash_creativity_num,
  bind_splash_cash_cost,
  channel_sales_name,
  pic_url,
  rgmv,
  substring(cast(dtm as string),1,6) as stat_month,
  substring(cast(dtm as string),7,2) as tag
from reddm.dm_ads_pub_spu_cvr_cost_1d_di 
where dtm=20230801 
)t1 
left join 
(select brand_account_id,
      direct_sales_dept1_name,
      direct_sales_dept2_name,
      direct_sales_dept3_name,
      direct_sales_dept4_name,
      direct_sales_dept5_name,
      direct_sales_dept6_name,
      direct_sales_name,
      operator_name,
      operator_code ,
      direct_sales_code,
      brand_user_name as brand_account_name,
      first_industry_name,
      second_industry_name,
      brand_group_tag_name,
      operator_name as cpc_operator_name
from redapp.app_ads_insight_industry_account_df
where dtm= (select max(dtm) from redapp.app_ads_insight_industry_account_df) 
)t2 
on t1.brand_account_id = t2.brand_account_id
left join 
(select spu_id,
  dtm,
  ti_level
from reddm.dm_ads_pub_spu_cvr_cost_1d_di 
where module = '整体'
group by spu_id,
  dtm,
  ti_level
)t3
on t3.spu_id = t1.spu_id and t3.dtm = t1.dtm
left join 
(select substring(stat_month,1,6) as stat_month,
  spu_id,
  module,
  taobao_rgmv_1m,
  tianmao_rgmv_1m
from redapp.app_ads_insight_ecm_spu_gmv_df
where dtm= (select max(dtm) from redapp.app_ads_insight_ecm_spu_gmv_df ) 
)t4
on t4.spu_id = t1.spu_id and t4.stat_month = t1.stat_month and t1.module = t4.module
where (case when taobao_rgmv_1m>0 or tianmao_rgmv_1m>0 then rgmv else 0 end )>0