select virtual_seller_id,
  product,
  market_target_type,
  virtual_seller_name,
  advertiser_id,
  t1.brand_account_id,
  brand_user_name,
  t2.brand_tag_code,
  t2.brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  case when direct_sales_dept3_name = '美奢潮流服饰行业' then '美奢洗护行业' when direct_sales_dept3_name = '生活服务行业' then '本地客户业务部' else direct_sales_dept3_name end as direct_sales_dept3_name,
  direct_sales_dept4_name,
  direct_sales_dept5_name,
  direct_sales_dept6_name,
  t2.brand_group_tag_code,
  t2.brand_group_tag_name,
  direct_sales_name,
  cpc_operator_name,
  cost_1h,
  ystd_cost_1h,
  cost_1d,
  ystd_cost_1d,
  coalesce(total_balance,0)-coalesce(cost_1d,0) as total_balance,
  case when budget_amt=99999999.99 then 0 else budget_amt end as budget_amt ,
   dtm,
  hh,
  ystd_budget_amt,
  brand_id,
  brand_name,
  coalesce(total_balance,0)-coalesce(cost_1d,0) as total_balance_1d,
  case when budget_amt=99999999.99 then 0 else budget_amt end as budget_amt_1d ,
  ystd_budget_amt as ystd_budget_amt_1d,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  coalesce(ystd_total_balance_1d,0)-coalesce(ystd_cost_1d,0) as ystd_total_balance_1d,
  coalesce(total_balance_before_1d,0)-coalesce(before_cost_1d,0) as before_total_balance_1d,
  budget_amt_before_1d as before_budget_amt_1d,
  track_budget_amt as track_budget_amt_1d,
  track_cost_1d,
  track_group_budget_amt as track_group_budget_amt_1d,
  track_group_cost_1d,
  valid_campaign_cnt as valid_campaign_cnt_1d,
  campaign_day_budget_income_amt as campaign_day_budget_income_amt_1d,
  limit_day_budget as limit_day_budget_1d,
  ystd_imp_cnt_1d,
  ystd_click_cnt_1d,
  before_imp_cnt_1d,
  before_click_cnt_1d,
  before_cost_1d,
  imp_cnt_1d,
  click_cnt_1d,
  rgmv_1d,
  purchase_order_gmv_7d_1d,
  out_click_rgmv_7d_1d,
  engage_cnt_1d,
  ystd_rgmv_1d,
  ystd_purchase_order_gmv_7d_1d,
  ystd_out_click_rgmv_7d_1d,
  ystd_engage_cnt_1d,
  before_rgmv_1d,
  before_purchase_order_gmv_7d_1d,
  before_out_click_rgmv_7d_1d,
  before_engage_cnt_1d,
  is_maxhh,
  before_out_click_rgmv_15d_1d,
  ystd_out_click_rgmv_15d_1d,
  out_click_rgmv_15d_1d,
  channel_sales_name,
  channel_operator_name,
  planner_name,
  oss_image,
  fail_creativity_diff_list,
  create_campaign_cnt,
  create_cost_campaign_cnt,
  cost_note_cnt,
  new_cost_note_cnt,
  cost_campaign_cnt,
  
  roi_1_campaign_list,
  roi_2_campaign_list,
  roi_3_campaign_list,
  roi_4_campaign_list,
  roi_5_campaign_list,
  concat_ws(',',coalesce(cpc_operator_name,'暂无运营'),coalesce(direct_sales_name,'暂无销售'),planner_name,coalesce(channel_operator_name,'暂无运营'),coalesce(channel_sales_name,'暂无销售')) as staff_name,
  live_gap_days,
  live_schedule_start_time,

  cpc_operator_dept3_name ,
  cpc_operator_dept4_name ,
  cpc_operator_dept5_name ,
  cpc_operator_dept6_name 
  from
  (select 

concat_ws(',',coalesce(cpc_operator_name,'暂无运营'),coalesce(direct_sales_name,'暂无销售'),planner_name,coalesce(channel_operator_name,'暂无运营'),coalesce(channel_sales_name,'暂无销售')) as staff_name,
 coalesce(imp_cnt_1d,0)-coalesce(before_imp_cnt_1d,0) as imp_cnt_1h,
  coalesce(click_cnt_1d,0)-coalesce(before_click_cnt_1d,0) as click_cnt_1h,
  coalesce(total_balance,0)-coalesce(cost_1d,0) as total_balance,
  case when budget_amt=99999999.99 then 0 else budget_amt end as budget_amt ,
  coalesce(total_balance,0)-coalesce(cost_1d,0) as total_balance_1d,
  case when budget_amt=99999999.99 then 0 else budget_amt end as budget_amt_1d ,
  ystd_budget_amt as ystd_budget_amt_1d,
  coalesce(ystd_total_balance_1d,0)-coalesce(ystd_cost_1d,0) as ystd_total_balance_1d,
  coalesce(total_balance_before_1d,0)-coalesce(before_cost_1d,0) as before_total_balance_1d,
  budget_amt_before_1d as before_budget_amt_1d,
  track_budget_amt as track_budget_amt_1d,
  track_group_budget_amt as track_group_budget_amt_1d,

  valid_campaign_cnt as valid_campaign_cnt_1d,
  campaign_day_budget_income_amt as campaign_day_budget_income_amt_1d,
  limit_day_budget as limit_day_budget_1d,
    virtual_seller_id,
  product,
  market_target_type,
  virtual_seller_name,
  advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
   direct_sales_dept3_name ,
  direct_sales_dept4_name,
  direct_sales_dept5_name,
  direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  direct_sales_name,
  cpc_operator_name,
  cost_1h,
  ystd_cost_1h,
  cost_1d,
  ystd_cost_1d,
  total_balance,
  --budget_amt ,
   dtm,
  hh,
  ystd_budget_amt ,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  ystd_total_balance_1d,
  total_balance_before_1d,
  --budget_amt_before_1d,
  --track_budget_amt,
  track_cost_1d,
  --track_group_budget_amt,
  track_group_cost_1d,
  --valid_campaign_cnt,
  --campaign_day_budget_income_amt,
  --limit_day_budget,
  ystd_imp_cnt_1d,
  ystd_click_cnt_1d,
  before_imp_cnt_1d,
  before_click_cnt_1d,
  before_cost_1d,
  imp_cnt_1d,
  click_cnt_1d,
  rgmv_1d,
  purchase_order_gmv_7d_1d,
  out_click_rgmv_7d_1d,
  engage_cnt_1d,
  ystd_rgmv_1d,
  ystd_purchase_order_gmv_7d_1d,
  ystd_out_click_rgmv_7d_1d,
  ystd_engage_cnt_1d,
  before_rgmv_1d,
  before_purchase_order_gmv_7d_1d,
  before_out_click_rgmv_7d_1d,
  before_engage_cnt_1d,
  is_maxhh,
  before_out_click_rgmv_15d_1d,
  ystd_out_click_rgmv_15d_1d,
  out_click_rgmv_15d_1d,
  channel_sales_name,
  channel_operator_name,
  planner_name,
  fail_creativity_diff_list,
  oss_image,
  create_campaign_cnt,
  create_cost_campaign_cnt,
  cost_note_cnt,
  cost_campaign_cnt,
  new_cost_note_cnt,
  case when roi_1_campaign_list='' then null else roi_1_campaign_list end as roi_1_campaign_list ,
  case when roi_1_campaign_list='' then null else roi_2_campaign_list end as roi_2_campaign_list,
  case when roi_1_campaign_list='' then null else roi_3_campaign_list end as roi_3_campaign_list,
  case when roi_1_campaign_list='' then null else roi_4_campaign_list end as roi_4_campaign_list,
  case when roi_1_campaign_list='' then null else roi_5_campaign_list end as roi_5_campaign_list,
  cpc_operator_dept1_name ,
  cpc_operator_dept2_name ,
  cpc_operator_dept3_name ,
  cpc_operator_dept4_name ,
  cpc_operator_dept5_name ,
  cpc_operator_dept6_name 
from reddm.dm_ads_rtb_advertiser_metric_hi
where dtm=(select max(dtm) from reddm.dm_ads_rtb_advertiser_metric_hi)
)t1 
left join 
(select brand_account_id,brand_id,brand_name,brand_tag_code,brand_tag_name,brand_group_tag_code,
  brand_group_tag_name
from redapp.app_ads_insight_account_diagnosis_info_df
where dtm=(select max(dtm) from redapp.app_ads_insight_account_diagnosis_info_df) and account_type = 1
)t2
on t1.brand_account_id = t2.brand_account_id
left join 
(select brand_account_id ,min(live_gap_days) as live_gap_days,group_concat(live_schedule_start_time) as live_schedule_start_time
from redapp.app_ads_insight_live_schedule_extend_df
where dtm=(select max(dtm) from redapp.app_ads_insight_live_schedule_extend_df) 
 and substring(live_schedule_start_time,1,10)=current_date
group by  brand_account_id
)t3
on t1.brand_account_id = t3.brand_account_id

