drop table
  if exists temp.dm_ads_rtb_advertiser_metric_hi_01{{ds_nodash}}_{{ts[11: 13]}}_sum;

create table
  temp.dm_ads_rtb_advertiser_metric_hi_01{{ds_nodash}}_{{ts[11: 13]}}_sum
select 1 as account_type,--1是子账户
  virtual_seller_id as account_id,
  virtual_seller_name as account_name,
  virtual_seller_id,
  virtual_seller_name,
  advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  max(direct_sales_dept3_name) as direct_sales_dept3_name,
  max(direct_sales_dept4_name) as direct_sales_dept4_name,
  max(direct_sales_dept5_name) as direct_sales_dept5_name,
  max(direct_sales_dept6_name) as direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  max(direct_sales_name) as direct_sales_name,
  max(cpc_operator_name) as cpc_operator_name,
  sum(cost_1h) as cost_1h,
  sum(ystd_cost_1h) as ystd_cost_1h,
  sum(cost_1d) as cost_1d,
  sum(ystd_cost_1d) as ystd_cost_1d,
  sum(total_balance) as total_balance,
  sum(case when market_target_type ='' and product = '' then budget_amt else 0 end) as budget_amt,
  sum(case when market_target_type ='' and product = '' then ystd_budget_amt else 0 end) as ystd_budget_amt,
  sum(ystd_total_balance_1d) as ystd_total_balance_1d,
  sum(total_balance_before_1d) as total_balance_before_1d,
  sum(case when market_target_type ='' and product = '' then budget_amt_before_1d else 0 end) as budget_amt_before_1d,
  max(case when market_target_type ='' and product = '' then track_budget_amt else 0 end) as track_budget_amt,
  max(case when market_target_type ='' and product = '' then track_cost_1d else 0 end) as track_cost_1d,
  max(case when market_target_type ='' and product = '' then track_group_budget_amt else 0 end) as track_group_budget_amt,
  max(case when market_target_type ='' and product = '' then track_group_cost_1d else 0 end) as track_group_cost_1d,
  sum(valid_campaign_cnt) as valid_campaign_cnt,
  sum(campaign_day_budget_income_amt) as campaign_day_budget_income_amt,
  sum(limit_day_budget) as limit_day_budget,
  sum(campaign_budget_income_amt) as campaign_budget_income_amt,
  sum(ystd_imp_cnt_1d) as ystd_imp_cnt_1d,
  sum(ystd_click_cnt_1d) as ystd_click_cnt_1d,
  sum(before_imp_cnt_1d) as before_imp_cnt_1d,
  sum(before_click_cnt_1d) as before_click_cnt_1d,
  sum(before_cost_1d) as before_cost_1d,
  sum(imp_cnt_1d) as imp_cnt_1d,
  sum(click_cnt_1d) as click_cnt_1d,
  sum(rgmv_1d) as rgmv_1d,
  sum(purchase_order_gmv_7d_1d) as purchase_order_gmv_7d_1d,
  sum(out_click_rgmv_7d_1d) as out_click_rgmv_7d_1d,
  sum(engage_cnt_1d) as engage_cnt_1d,
  sum(ystd_rgmv_1d) as ystd_rgmv_1d,
  sum(ystd_purchase_order_gmv_7d_1d) as ystd_purchase_order_gmv_7d_1d,
  sum(ystd_out_click_rgmv_7d_1d) as ystd_out_click_rgmv_7d_1d,
  sum(ystd_engage_cnt_1d) as ystd_engage_cnt_1d,
  sum(before_rgmv_1d) as before_rgmv_1d,
  sum(before_purchase_order_gmv_7d_1d) as before_purchase_order_gmv_7d_1d,
  sum(before_out_click_rgmv_7d_1d) as before_out_click_rgmv_7d_1d,
  sum(before_engage_cnt_1d) as before_engage_cnt_1d,
--分营销目的消耗，预算，rgmv，互动
sum(case when market_target_type ='种草' then cost_1d else 0 end) as ti_cost_1d,
sum(case when market_target_type ='种草' then ystd_cost_1d else 0 end) as ti_ystd_cost_1d,
sum(case when market_target_type ='种草' then before_cost_1d else 0 end) as ti_before_cost_1d,

sum(case when market_target_type ='线索' then cost_1d else 0 end) as leads_cost_1d,
sum(case when market_target_type ='线索' then ystd_cost_1d else 0 end) as leads_ystd_cost_1d,
sum(case when market_target_type ='线索' then before_cost_1d else 0 end) as leads_before_cost_1d,

sum(case when market_target_type ='闭环电商' then cost_1d else 0 end) as ecm_closed_cost_1d,
sum(case when market_target_type ='闭环电商' then ystd_cost_1d else 0 end) as ecm_closed_ystd_cost_1d,
sum(case when market_target_type ='闭环电商' then before_cost_1d else 0 end) as ecm_closed_before_cost_1d,

sum(case when market_target_type ='非闭环电商' then cost_1d else 0 end) as ecm_unclosed_cost_1d,
sum(case when market_target_type ='非闭环电商' then ystd_cost_1d else 0 end) as ecm_unclosed_ystd_cost_1d,
sum(case when market_target_type ='非闭环电商' then before_cost_1d else 0 end) as ecm_unclosed_before_cost_1d,

sum(case when market_target_type ='种草' then engage_cnt_1d else 0 end) as ti_engage_cnt_1d,
sum(case when market_target_type ='种草' then ystd_engage_cnt_1d else 0 end) as ti_ystd_engage_cnt_1d,
sum(case when market_target_type ='种草' then before_engage_cnt_1d else 0 end) as ti_before_engage_cnt_1d,

sum(case when market_target_type ='线索' then engage_cnt_1d else 0 end) as leads_engage_cnt_1d,
sum(case when market_target_type ='线索' then ystd_engage_cnt_1d else 0 end) as leads_ystd_engage_cnt_1d,
sum(case when market_target_type ='线索' then before_engage_cnt_1d else 0 end) as leads_before_engage_cnt_1d,

sum(case when market_target_type ='闭环电商' then engage_cnt_1d else 0 end) as ecm_closed_engage_cnt_1d,
sum(case when market_target_type ='闭环电商' then ystd_engage_cnt_1d else 0 end) as ecm_closed_ystd_engage_cnt_1d,
sum(case when market_target_type ='闭环电商' then before_engage_cnt_1d else 0 end) as ecm_closed_before_engage_cnt_1d,

sum(case when market_target_type ='非闭环电商' then engage_cnt_1d else 0 end) as ecm_unclosed_engage_cnt_1d,
sum(case when market_target_type ='非闭环电商' then ystd_engage_cnt_1d else 0 end) as ecm_unclosed_ystd_engage_cnt_1d,
sum(case when market_target_type ='非闭环电商' then before_engage_cnt_1d else 0 end) as ecm_unclosed_before_engage_cnt_1d,
--预算
sum(case when market_target_type ='种草' then budget_amt else 0 end) as ti_budget_amt_1d,
sum(case when market_target_type ='种草' then ystd_budget_amt else 0 end) as ti_ystd_budget_amt_1d,
sum(case when market_target_type ='种草' then budget_amt_before_1d else 0 end) as ti_before_budget_amt_1d,

sum(case when market_target_type ='线索' then budget_amt else 0 end) as leads_budget_amt_1d,
sum(case when market_target_type ='线索' then ystd_budget_amt else 0 end) as leads_ystd_budget_amt_1d,
sum(case when market_target_type ='线索' then budget_amt_before_1d else 0 end) as leads_before_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then budget_amt else 0 end) as ecm_closed_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then ystd_budget_amt else 0 end) as ecm_closed_ystd_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then budget_amt_before_1d else 0 end) as ecm_closed_before_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then budget_amt else 0 end) as ecm_unclosed_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then ystd_budget_amt else 0 end) as ecm_unclosed_ystd_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then budget_amt_before_1d else 0 end) as ecm_unclosed_before_budget_amt_1d,
--gmv
sum(case when market_target_type ='闭环电商' then rgmv_1d else 0 end) as ecm_closed_rgmv_1d,
sum(case when market_target_type ='闭环电商' then ystd_rgmv_1d else 0 end) as ecm_closed_ystd_rgmv_1d,
sum(case when market_target_type ='闭环电商' then before_rgmv_1d else 0 end) as ecm_closed_before_rgmv_1d,
sum(case when market_target_type ='闭环电商' then purchase_order_gmv_7d_1d else 0 end) as ecm_closed_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='闭环电商' then ystd_purchase_order_gmv_7d_1d else 0 end) as ecm_closed_ystd_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='闭环电商' then before_purchase_order_gmv_7d_1d else 0 end) as ecm_closed_before_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_out_click_rgmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then ystd_out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_ystd_out_click_rgmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then before_out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_before_out_click_rgmv_7d_1d


from
  redcdm.dm_ads_rtb_advertiser_metric_hi
where
  dtm = '{{ds_nodash}}'
  and hh = (
    select
      max(hh)
    from
      redcdm.dm_ads_rtb_advertiser_metric_hi
    where
      dtm = '{{ds_nodash}}'
  )
group by
  virtual_seller_id,
  virtual_seller_name,
  advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  brand_group_tag_code,
  brand_group_tag_name,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name


  union all 
  select 2 as account_type,--2代理商
  agent_user_id as account_id,
  agent_user_name as account_name,
  '' as virtual_seller_id,
  '' as virtual_seller_name,
  '' as advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  max(direct_sales_dept3_name) as direct_sales_dept3_name,
  max(direct_sales_dept4_name) as direct_sales_dept4_name,
  max(direct_sales_dept5_name) as direct_sales_dept5_name,
  max(direct_sales_dept6_name) as direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  max(direct_sales_name) as direct_sales_name,
  max(cpc_operator_name) as cpc_operator_name,
  sum(cost_1h) as cost_1h,
  sum(ystd_cost_1h) as ystd_cost_1h,
  sum(cost_1d) as cost_1d,
  sum(ystd_cost_1d) as ystd_cost_1d,
  sum(total_balance) as total_balance,
  sum(case when market_target_type ='' and product = '' then budget_amt else 0 end) as budget_amt,
  sum(case when market_target_type ='' and product = '' then ystd_budget_amt else 0 end) as ystd_budget_amt,
  sum(ystd_total_balance_1d) as ystd_total_balance_1d,
  sum(total_balance_before_1d) as total_balance_before_1d,
  sum(case when market_target_type ='' and product = '' then budget_amt_before_1d else 0 end) as budget_amt_before_1d,
  max(case when market_target_type ='' and product = '' then track_budget_amt else 0 end) as track_budget_amt,
  max(case when market_target_type ='' and product = '' then track_cost_1d else 0 end) as track_cost_1d,
  max(case when market_target_type ='' and product = '' then track_group_budget_amt else 0 end) as track_group_budget_amt,
  max(case when market_target_type ='' and product = '' then track_group_cost_1d else 0 end) as track_group_cost_1d,
  sum(valid_campaign_cnt) as valid_campaign_cnt,
  sum(campaign_day_budget_income_amt) as campaign_day_budget_income_amt,
  sum(limit_day_budget) as limit_day_budget,
  sum(campaign_budget_income_amt) as campaign_budget_income_amt,
  sum(ystd_imp_cnt_1d) as ystd_imp_cnt_1d,
  sum(ystd_click_cnt_1d) as ystd_click_cnt_1d,
  sum(before_imp_cnt_1d) as before_imp_cnt_1d,
  sum(before_click_cnt_1d) as before_click_cnt_1d,
  sum(before_cost_1d) as before_cost_1d,
  sum(imp_cnt_1d) as imp_cnt_1d,
  sum(click_cnt_1d) as click_cnt_1d,
  sum(rgmv_1d) as rgmv_1d,
  sum(purchase_order_gmv_7d_1d) as purchase_order_gmv_7d_1d,
  sum(out_click_rgmv_7d_1d) as out_click_rgmv_7d_1d,
  sum(engage_cnt_1d) as engage_cnt_1d,
  sum(ystd_rgmv_1d) as ystd_rgmv_1d,
  sum(ystd_purchase_order_gmv_7d_1d) as ystd_purchase_order_gmv_7d_1d,
  sum(ystd_out_click_rgmv_7d_1d) as ystd_out_click_rgmv_7d_1d,
  sum(ystd_engage_cnt_1d) as ystd_engage_cnt_1d,
  sum(before_rgmv_1d) as before_rgmv_1d,
  sum(before_purchase_order_gmv_7d_1d) as before_purchase_order_gmv_7d_1d,
  sum(before_out_click_rgmv_7d_1d) as before_out_click_rgmv_7d_1d,
  sum(before_engage_cnt_1d) as before_engage_cnt_1d,
--分营销目的消耗，预算，rgmv，互动
sum(case when market_target_type ='种草' then cost_1d else 0 end) as ti_cost_1d,
sum(case when market_target_type ='种草' then ystd_cost_1d else 0 end) as ti_ystd_cost_1d,
sum(case when market_target_type ='种草' then before_cost_1d else 0 end) as ti_before_cost_1d,

sum(case when market_target_type ='线索' then cost_1d else 0 end) as leads_cost_1d,
sum(case when market_target_type ='线索' then ystd_cost_1d else 0 end) as leads_ystd_cost_1d,
sum(case when market_target_type ='线索' then before_cost_1d else 0 end) as leads_before_cost_1d,

sum(case when market_target_type ='闭环电商' then cost_1d else 0 end) as ecm_closed_cost_1d,
sum(case when market_target_type ='闭环电商' then ystd_cost_1d else 0 end) as ecm_closed_ystd_cost_1d,
sum(case when market_target_type ='闭环电商' then before_cost_1d else 0 end) as ecm_closed_before_cost_1d,

sum(case when market_target_type ='非闭环电商' then cost_1d else 0 end) as ecm_unclosed_cost_1d,
sum(case when market_target_type ='非闭环电商' then ystd_cost_1d else 0 end) as ecm_unclosed_ystd_cost_1d,
sum(case when market_target_type ='非闭环电商' then before_cost_1d else 0 end) as ecm_unclosed_before_cost_1d,

sum(case when market_target_type ='种草' then engage_cnt_1d else 0 end) as ti_engage_cnt_1d,
sum(case when market_target_type ='种草' then ystd_engage_cnt_1d else 0 end) as ti_ystd_engage_cnt_1d,
sum(case when market_target_type ='种草' then before_engage_cnt_1d else 0 end) as ti_before_engage_cnt_1d,

sum(case when market_target_type ='线索' then engage_cnt_1d else 0 end) as leads_engage_cnt_1d,
sum(case when market_target_type ='线索' then ystd_engage_cnt_1d else 0 end) as leads_ystd_engage_cnt_1d,
sum(case when market_target_type ='线索' then before_engage_cnt_1d else 0 end) as leads_before_engage_cnt_1d,

sum(case when market_target_type ='闭环电商' then engage_cnt_1d else 0 end) as ecm_closed_engage_cnt_1d,
sum(case when market_target_type ='闭环电商' then ystd_engage_cnt_1d else 0 end) as ecm_closed_ystd_engage_cnt_1d,
sum(case when market_target_type ='闭环电商' then before_engage_cnt_1d else 0 end) as ecm_closed_before_engage_cnt_1d,

sum(case when market_target_type ='非闭环电商' then engage_cnt_1d else 0 end) as ecm_unclosed_engage_cnt_1d,
sum(case when market_target_type ='非闭环电商' then ystd_engage_cnt_1d else 0 end) as ecm_unclosed_ystd_engage_cnt_1d,
sum(case when market_target_type ='非闭环电商' then before_engage_cnt_1d else 0 end) as ecm_unclosed_before_engage_cnt_1d,
--预算
sum(case when market_target_type ='种草' then budget_amt else 0 end) as ti_budget_amt_1d,
sum(case when market_target_type ='种草' then ystd_budget_amt else 0 end) as ti_ystd_budget_amt_1d,
sum(case when market_target_type ='种草' then budget_amt_before_1d else 0 end) as ti_before_budget_amt_1d,

sum(case when market_target_type ='线索' then budget_amt else 0 end) as leads_budget_amt_1d,
sum(case when market_target_type ='线索' then ystd_budget_amt else 0 end) as leads_ystd_budget_amt_1d,
sum(case when market_target_type ='线索' then budget_amt_before_1d else 0 end) as leads_before_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then budget_amt else 0 end) as ecm_closed_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then ystd_budget_amt else 0 end) as ecm_closed_ystd_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then budget_amt_before_1d else 0 end) as ecm_closed_before_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then budget_amt else 0 end) as ecm_unclosed_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then ystd_budget_amt else 0 end) as ecm_unclosed_ystd_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then budget_amt_before_1d else 0 end) as ecm_unclosed_before_budget_amt_1d,
--gmv
sum(case when market_target_type ='闭环电商' then rgmv_1d else 0 end) as ecm_closed_rgmv_1d,
sum(case when market_target_type ='闭环电商' then ystd_rgmv_1d else 0 end) as ecm_closed_ystd_rgmv_1d,
sum(case when market_target_type ='闭环电商' then before_rgmv_1d else 0 end) as ecm_closed_before_rgmv_1d,
sum(case when market_target_type ='闭环电商' then purchase_order_gmv_7d_1d else 0 end) as ecm_closed_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='闭环电商' then ystd_purchase_order_gmv_7d_1d else 0 end) as ecm_closed_ystd_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='闭环电商' then before_purchase_order_gmv_7d_1d else 0 end) as ecm_closed_before_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_out_click_rgmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then ystd_out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_ystd_out_click_rgmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then before_out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_before_out_click_rgmv_7d_1d


from
  redcdm.dm_ads_rtb_advertiser_metric_hi
where
  dtm = '{{ds_nodash}}'
  and hh = (
    select
      max(hh)
    from
      redcdm.dm_ads_rtb_advertiser_metric_hi
    where
      dtm = '{{ds_nodash}}'
  )
group by
  -- virtual_seller_id,
  -- virtual_seller_name,
  -- advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  brand_group_tag_code,
  brand_group_tag_name,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name
  union all
  select 3 as account_type,--1是子账户
  brand_account_id as account_id,
  brand_user_name as account_name,
  '' as virtual_seller_id,
  '' as virtual_seller_name,
  '' as advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  '' as agent_user_id,
  '' as agent_user_name,
  '' as agent_company_code,
  '' as agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  max(direct_sales_dept3_name) as direct_sales_dept3_name,
  max(direct_sales_dept4_name) as direct_sales_dept4_name,
  max(direct_sales_dept5_name) as direct_sales_dept5_name,
  max(direct_sales_dept6_name) as direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  max(direct_sales_name) as direct_sales_name,
  max(cpc_operator_name) as cpc_operator_name,
  sum(cost_1h) as cost_1h,
  sum(ystd_cost_1h) as ystd_cost_1h,
  sum(cost_1d) as cost_1d,
  sum(ystd_cost_1d) as ystd_cost_1d,
  sum(total_balance) as total_balance,
  sum(case when market_target_type ='' and product = '' then budget_amt else 0 end) as budget_amt,
  sum(case when market_target_type ='' and product = '' then ystd_budget_amt else 0 end) as ystd_budget_amt,
  sum(ystd_total_balance_1d) as ystd_total_balance_1d,
  sum(total_balance_before_1d) as total_balance_before_1d,
  sum(case when market_target_type ='' and product = '' then budget_amt_before_1d else 0 end) as budget_amt_before_1d,
  max(case when market_target_type ='' and product = '' then track_budget_amt else 0 end) as track_budget_amt,
  max(case when market_target_type ='' and product = '' then track_cost_1d else 0 end) as track_cost_1d,
  max(case when market_target_type ='' and product = '' then track_group_budget_amt else 0 end) as track_group_budget_amt,
  max(case when market_target_type ='' and product = '' then track_group_cost_1d else 0 end) as track_group_cost_1d,
  sum(valid_campaign_cnt) as valid_campaign_cnt,
  sum(campaign_day_budget_income_amt) as campaign_day_budget_income_amt,
  sum(limit_day_budget) as limit_day_budget,
  sum(campaign_budget_income_amt) as campaign_budget_income_amt,
  sum(ystd_imp_cnt_1d) as ystd_imp_cnt_1d,
  sum(ystd_click_cnt_1d) as ystd_click_cnt_1d,
  sum(before_imp_cnt_1d) as before_imp_cnt_1d,
  sum(before_click_cnt_1d) as before_click_cnt_1d,
  sum(before_cost_1d) as before_cost_1d,
  sum(imp_cnt_1d) as imp_cnt_1d,
  sum(click_cnt_1d) as click_cnt_1d,
  sum(rgmv_1d) as rgmv_1d,
  sum(purchase_order_gmv_7d_1d) as purchase_order_gmv_7d_1d,
  sum(out_click_rgmv_7d_1d) as out_click_rgmv_7d_1d,
  sum(engage_cnt_1d) as engage_cnt_1d,
  sum(ystd_rgmv_1d) as ystd_rgmv_1d,
  sum(ystd_purchase_order_gmv_7d_1d) as ystd_purchase_order_gmv_7d_1d,
  sum(ystd_out_click_rgmv_7d_1d) as ystd_out_click_rgmv_7d_1d,
  sum(ystd_engage_cnt_1d) as ystd_engage_cnt_1d,
  sum(before_rgmv_1d) as before_rgmv_1d,
  sum(before_purchase_order_gmv_7d_1d) as before_purchase_order_gmv_7d_1d,
  sum(before_out_click_rgmv_7d_1d) as before_out_click_rgmv_7d_1d,
  sum(before_engage_cnt_1d) as before_engage_cnt_1d,
--分营销目的消耗，预算，rgmv，互动
sum(case when market_target_type ='种草' then cost_1d else 0 end) as ti_cost_1d,
sum(case when market_target_type ='种草' then ystd_cost_1d else 0 end) as ti_ystd_cost_1d,
sum(case when market_target_type ='种草' then before_cost_1d else 0 end) as ti_before_cost_1d,

sum(case when market_target_type ='线索' then cost_1d else 0 end) as leads_cost_1d,
sum(case when market_target_type ='线索' then ystd_cost_1d else 0 end) as leads_ystd_cost_1d,
sum(case when market_target_type ='线索' then before_cost_1d else 0 end) as leads_before_cost_1d,

sum(case when market_target_type ='闭环电商' then cost_1d else 0 end) as ecm_closed_cost_1d,
sum(case when market_target_type ='闭环电商' then ystd_cost_1d else 0 end) as ecm_closed_ystd_cost_1d,
sum(case when market_target_type ='闭环电商' then before_cost_1d else 0 end) as ecm_closed_before_cost_1d,

sum(case when market_target_type ='非闭环电商' then cost_1d else 0 end) as ecm_unclosed_cost_1d,
sum(case when market_target_type ='非闭环电商' then ystd_cost_1d else 0 end) as ecm_unclosed_ystd_cost_1d,
sum(case when market_target_type ='非闭环电商' then before_cost_1d else 0 end) as ecm_unclosed_before_cost_1d,

sum(case when market_target_type ='种草' then engage_cnt_1d else 0 end) as ti_engage_cnt_1d,
sum(case when market_target_type ='种草' then ystd_engage_cnt_1d else 0 end) as ti_ystd_engage_cnt_1d,
sum(case when market_target_type ='种草' then before_engage_cnt_1d else 0 end) as ti_before_engage_cnt_1d,

sum(case when market_target_type ='线索' then engage_cnt_1d else 0 end) as leads_engage_cnt_1d,
sum(case when market_target_type ='线索' then ystd_engage_cnt_1d else 0 end) as leads_ystd_engage_cnt_1d,
sum(case when market_target_type ='线索' then before_engage_cnt_1d else 0 end) as leads_before_engage_cnt_1d,

sum(case when market_target_type ='闭环电商' then engage_cnt_1d else 0 end) as ecm_closed_engage_cnt_1d,
sum(case when market_target_type ='闭环电商' then ystd_engage_cnt_1d else 0 end) as ecm_closed_ystd_engage_cnt_1d,
sum(case when market_target_type ='闭环电商' then before_engage_cnt_1d else 0 end) as ecm_closed_before_engage_cnt_1d,

sum(case when market_target_type ='非闭环电商' then engage_cnt_1d else 0 end) as ecm_unclosed_engage_cnt_1d,
sum(case when market_target_type ='非闭环电商' then ystd_engage_cnt_1d else 0 end) as ecm_unclosed_ystd_engage_cnt_1d,
sum(case when market_target_type ='非闭环电商' then before_engage_cnt_1d else 0 end) as ecm_unclosed_before_engage_cnt_1d,
--预算
sum(case when market_target_type ='种草' then budget_amt else 0 end) as ti_budget_amt_1d,
sum(case when market_target_type ='种草' then ystd_budget_amt else 0 end) as ti_ystd_budget_amt_1d,
sum(case when market_target_type ='种草' then budget_amt_before_1d else 0 end) as ti_before_budget_amt_1d,

sum(case when market_target_type ='线索' then budget_amt else 0 end) as leads_budget_amt_1d,
sum(case when market_target_type ='线索' then ystd_budget_amt else 0 end) as leads_ystd_budget_amt_1d,
sum(case when market_target_type ='线索' then budget_amt_before_1d else 0 end) as leads_before_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then budget_amt else 0 end) as ecm_closed_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then ystd_budget_amt else 0 end) as ecm_closed_ystd_budget_amt_1d,
sum(case when market_target_type ='闭环电商' then budget_amt_before_1d else 0 end) as ecm_closed_before_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then budget_amt else 0 end) as ecm_unclosed_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then ystd_budget_amt else 0 end) as ecm_unclosed_ystd_budget_amt_1d,
sum(case when market_target_type ='非闭环电商' then budget_amt_before_1d else 0 end) as ecm_unclosed_before_budget_amt_1d,
--gmv
sum(case when market_target_type ='闭环电商' then rgmv_1d else 0 end) as ecm_closed_rgmv_1d,
sum(case when market_target_type ='闭环电商' then ystd_rgmv_1d else 0 end) as ecm_closed_ystd_rgmv_1d,
sum(case when market_target_type ='闭环电商' then before_rgmv_1d else 0 end) as ecm_closed_before_rgmv_1d,
sum(case when market_target_type ='闭环电商' then purchase_order_gmv_7d_1d else 0 end) as ecm_closed_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='闭环电商' then ystd_purchase_order_gmv_7d_1d else 0 end) as ecm_closed_ystd_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='闭环电商' then before_purchase_order_gmv_7d_1d else 0 end) as ecm_closed_before_purchase_order_gmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_out_click_rgmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then ystd_out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_ystd_out_click_rgmv_7d_1d,
sum(case when market_target_type ='非闭环电商' then before_out_click_rgmv_7d_1d else 0 end) as ecm_unclosed_before_out_click_rgmv_7d_1d


from
  redcdm.dm_ads_rtb_advertiser_metric_hi
where
  dtm = '{{ds_nodash}}'
  and hh = (
    select
      max(hh)
    from
      redcdm.dm_ads_rtb_advertiser_metric_hi
    where
      dtm = '{{ds_nodash}}'
  )
group by
  -- virtual_seller_id,
  -- virtual_seller_name,
  -- advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  -- agent_user_id,
  -- agent_user_name,
  -- agent_company_code,
  -- agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  brand_group_tag_code,
  brand_group_tag_name,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name