CREATE EXTERNAL TABLE `redapp.app_ads_insight_advertiser_product_diagnosis_info_df` (
(`brand_account_id` string COMMENT '企业号id', 
  `advertiser_id` string COMMENT '广告主id', 
  `v_seller_id` string COMMENT '虚拟店铺ID$$需求文档信息见：https://doc.weixin.qq.com/sheet/e3_AXMAUgbyAPoBweIS3iTSDSTBuslco?scode=ANAAyQcbAAgq1aZ8y0AdoA0wYOAIE&tab=9nth2c', 
  `v_seller_name` string COMMENT '虚拟店铺名称', 
  `agent_user_id` string COMMENT '代理商user_id', 
  `agent_user_name` string COMMENT '代理商名称', 
 `module` string COMMENT '广告类型：效果|品牌|薯条|品合', 
  `product` string COMMENT '产品： 信息流|搜索|视频内流|搜索第三位|开屏|品牌专区|信息流GD|火焰话题|惊喜盒子|竞价CPM', 
 `marketing_target` string COMMENT '营销目标$$营销诉求:3-商品销量 4-产品种草 6-品牌知名度 7-品牌意向 8-直播推广 9-客资收集 10-抢占关键词 11-抢占人群 12-加粉 13-行业商品推广', 
  `market_target` string COMMENT '营销目标，枚举值为：线索，种草，闭环电商、非闭环电商', 
`brand_account_name` string COMMENT '企业号名称', 
`company_code` string COMMENT '客户code', 
  `company_name` string COMMENT '客户名称', 
   `track_group_name` string COMMENT '赛道名称', 
  
  `direct_sales_name` string COMMENT '销售姓名', 
  `direct_sales_dept1_name` string COMMENT '销售1级部门', 
  `direct_sales_dept2_name` string COMMENT '销售2级部门', 
 `direct_sales_dept3_name` string COMMENT '销售3级部门', 
  `direct_sales_dept4_name` string COMMENT '销售4级部门', 
  `direct_sales_dept5_name` string COMMENT '销售5级部门', 
  `direct_sales_dept6_name` string COMMENT '销售6级部门', 
  `brand_group_tag_code` string COMMENT '品牌的集团编码（优先取brand_tag_code,再取group_code）', 
  `brand_group_tag_name` string COMMENT '品牌的集团名称（优先取brand_tag_name,再取group_name）', 
   `cpc_operator_code` string COMMENT '运营code', 
   `cpc_operator_name` string COMMENT '运营姓名', 
 `first_industry_name` string COMMENT '一级行业名称', 
  `second_industry_name` string COMMENT '二级行业名称', 
 `track_industry_name` string COMMENT '赛道行业', 
  `track_detail_name` string COMMENT '赛道明细', 
  `brand_id` bigint COMMENT '品牌id', 
  `brand_name` string COMMENT '品牌名称', 
  `planner_name` string COMMENT '策划$$来自文档上传，多个用，隔开',
  staff_name string comment'员工list',
----redbi使用赛道逻辑
 process_track_industry_name string COMMENT '赛道行业（处理后）', 
  process_track_group_name string COMMENT '一级赛道（处理后）', 
  process_track_second_name string COMMENT '二级赛道（处理后）', 
  process_track_third_name string COMMENT '三级赛道（处理后）', 
 `channel_sales_name` string COMMENT '代理渠道销售', 
  `channel_sales_code` string COMMENT '代理渠道销售code', 
  `channel_operator_name` string COMMENT '渠道运营', 

  `ecm_closed_dgmv_2m` double COMMENT '本双月电商闭环dgmv', 
  `cps_note_num_2m` bigint COMMENT '本双月发布cps笔记数量', 
  `s_live_dgmv_2m` double COMMENT '电商店播gmv'
   `is_sx_ti` bigint COMMENT '商销且双月有投放过种草人群', 
  `taolian_cash_income_amt_2m` double COMMENT '本双月小红星广告流水', 
 `bcoo_cash_income_amt_2m` double COMMENT '本双月品合总流水', 
   `track_taolian_cash_income_amt_2m` double COMMENT '本双月小红星总流水', 
`track_bcoo_cash_income_amt_2m` double COMMENT '本双月品合总流水', 
  --ecm_closed_dgmv_2m,
  `ecm_closed_dgmv_cash_income_amt_2m` double COMMENT '本双月dgmv>0的电商闭环流水',
  `track_ecm_closed_dgmv_2m` double COMMENT '本双月电商闭环dgmv', 
   `track_ecm_closed_dgmv_cash_income_amt_2m` double COMMENT '本双月dgmv>0的电商闭环流水', 

  `cash_income_amt` double COMMENT '现金消耗$$单位-元', 
  `income_amt` double COMMENT '运营消耗$$单位-元', 
  `imp_cnt` bigint COMMENT '曝光量', 
  `click_cnt` bigint COMMENT '点击量', 
  `like_cnt` bigint COMMENT '点赞量', 
  `fav_cnt` bigint COMMENT '收藏量', 
  `cmt_cnt` bigint COMMENT '评论量', 
  `share_cnt` bigint COMMENT '分享量', 
  `follow_cnt` bigint COMMENT '关注量', 
  `screenshot_cnt` bigint COMMENT '截屏数', 
  engage_cnt bigint COMMENT '互动数', 
  `click_rgmv_7d` double COMMENT '7天点击口径购买rgmv,单位元$$新转化表redcdm.dws_ads_cvr_creativity_1d_di，    sum(coalesce(purchase_rgmv,0)+coalesce(mini_purchase_rgmv,0)) as click_rgmv_7d', 
  `conversion_cnt` bigint COMMENT '转化量，即文档中线索量$$20230605及以后有数', 
  ecm_unclosed_rgmv double COMMENT'非闭环电商rgmv',
  rtb_cost_income_amt double COMMENT'分场域营销目的预算使用率分子',
  rtb_budget_income_amt double COMMENT'分场域营销目的预算使用率分母',
  cost_income_amt double COMMENT'分场域预算使用率分子',
  budget_income_amt double COMMENT'分场域预算使用率分母',
  advertiser_budget_income_amt double COMMENT'预算使用率分母',
  advertiser_cost_income_amt double COMMENT'预算使用率分子',
  cash_balance double COMMENT'余额',
  --cash_balance_days,redbi配置
  -------------前一日--------------
  ystd_cash_income_amt_1d  double COMMENT '前一日现金消耗$$单位-元', 
ystd_income_amt_1d  double COMMENT '前一日运营消耗$$单位-元', 
ystd_imp_cnt_1d  bigint COMMENT '前一日曝光量', 
ystd_click_cnt_1d  bigint COMMENT '前一日点击量', 
ystd_like_cnt_1d  bigint COMMENT '前一日点赞量', 
ystd_fav_cnt_1d  bigint COMMENT '前一日收藏量', 
ystd_cmt_cnt_1d  bigint COMMENT '前一日评论量', 
ystd_share_cnt_1d  bigint COMMENT '前一日分享量', 
ystd_follow_cnt_1d  bigint COMMENT '前一日关注量', 
ystd_screenshot_cnt_1d  bigint COMMENT '前一日截屏数', 
ystd_engage_cnt bigint COMMENT '前一日互动数', 
ystd_click_rgmv_7d_1d  double COMMENT '前一日7天点击口径购买rgmv,单位元$$新转化表redcdm.dws_ads_cvr_creativity_1d_di，ystd_sum(coalesce(purchase_rgmv,0)+coalesce(mini_purchase_rgmv,0)) as click_rgmv_7d', 
ystd_conversion_cnt_1d  bigint COMMENT '前一日转化量，即文档中线索量$$20230605及以后有数', 
ystd_ecm_unclosed_rgmv_1d  double COMMENT'前一日非闭环电商rgmv',
ystd_rtb_cost_income_amt_1d  double COMMENT'前一日分场域营销目的预算使用率分子',
ystd_rtb_budget_income_amt_1d  double COMMENT'前一日分场域营销目的预算使用率分母',
ystd_cost_income_amt_1d  double COMMENT'前一日分场域预算使用率分子',
ystd_budget_income_amt_1d  double COMMENT'前一日分场域预算使用率分母',
ystd_advertiser_budget_income_amt_1d  double COMMENT'前一日预算使用率分母',
ystd_advertiser_cost_income_amt_1d  double COMMENT'前一日预算使用率分子',
ystd_cash_balance_1d  double COMMENT'前一日余额',
--------------------本双月----------------
  cash_income_amt_2m  double COMMENT '本双月现金消耗$$单位-元', 
income_amt_2m  double COMMENT '本双月运营消耗$$单位-元', 
imp_cnt_2m  bigint COMMENT '本双月曝光量', 
click_cnt_2m  bigint COMMENT '本双月点击量', 
like_cnt_2m  bigint COMMENT '本双月点赞量', 
fav_cnt_2m  bigint COMMENT '本双月收藏量', 
cmt_cnt_2m  bigint COMMENT '本双月评论量', 
share_cnt_2m  bigint COMMENT '本双月分享量', 
follow_cnt_2m  bigint COMMENT '本双月关注量', 
screenshot_cnt_2m  bigint COMMENT '本双月截屏数', 
engage_cnt bigint COMMENT '本双月互动数', 
click_rgmv_7d_2m  double COMMENT '本双月7天点击口径购买rgmv,单位元$$新转化表redcdm.dws_ads_cvr_creativity_2m_di，sum(coalesce(purchase_rgmv,0)+coalesce(mini_purchase_rgmv,0)) as click_rgmv_7d', 
conversion_cnt_2m  bigint COMMENT '本双月转化量，即文档中线索量$$20230605及以后有数', 
ecm_unclosed_rgmv_2m  double COMMENT'本双月非闭环电商rgmv',
rtb_cost_income_amt_2m  double COMMENT'本双月分场域营销目的预算使用率分子',
rtb_budget_income_amt_2m  double COMMENT'本双月分场域营销目的预算使用率分母',
cost_income_amt_2m  double COMMENT'本双月分场域预算使用率分子',
budget_income_amt_2m  double COMMENT'本双月分场域预算使用率分母',
advertiser_budget_income_amt_2m  double COMMENT'本双月预算使用率分母',
advertiser_cost_income_amt_2m  double COMMENT'本双月预算使用率分子',
cash_balance_2m  double COMMENT'本双月余额',
    ------------------去年双月-----------------
   cash_income_amt_last_2m  double COMMENT '去年双月现金消耗$$单位-元', 
income_amt_last_2m  double COMMENT '去年双月运营消耗$$单位-元', 
imp_cnt_last_2m  bigint COMMENT '去年双月曝光量', 
click_cnt_last_2m  bigint COMMENT '去年双月点击量', 
like_cnt_last_2m  bigint COMMENT '去年双月点赞量', 
fav_cnt_last_2m  bigint COMMENT '去年双月收藏量', 
cmt_cnt_last_2m  bigint COMMENT '去年双月评论量', 
share_cnt_last_2m  bigint COMMENT '去年双月分享量', 
follow_cnt_last_2m  bigint COMMENT '去年双月关注量', 
screenshot_cnt_last_2m  bigint COMMENT '去年双月截屏数', 
engage_cnt bigint COMMENT '去年双月互动数', 
click_rgmv_7d_last_2m  double COMMENT '去年双月7天点击口径购买rgmv,单位元$$新转化表redcdm.dws_ads_cvr_creativity_last_2m_di，sum(coalesce(purchase_rgmv,0)+coalesce(mini_purchase_rgmv,0)) as click_rgmv_7d', 
conversion_cnt_last_2m  bigint COMMENT '去年双月转化量，即文档中线索量$$20230605及以后有数', 
ecm_unclosed_rgmv_last_2m  double COMMENT'去年双月非闭环电商rgmv',
rtb_cost_income_amt_last_2m  double COMMENT'去年双月分场域营销目的预算使用率分子',
rtb_budget_income_amt_last_2m  double COMMENT'去年双月分场域营销目的预算使用率分母',
cost_income_amt_last_2m  double COMMENT'去年双月分场域预算使用率分子',
budget_income_amt_last_2m  double COMMENT'去年双月分场域预算使用率分母',
advertiser_budget_income_amt_last_2m  double COMMENT'去年双月预算使用率分母',
advertiser_cost_income_amt_last_2m  double COMMENT'去年双月预算使用率分子',
cash_balance_last_2m  double COMMENT'去年双月余额',
    -------------上双月--------------------
    cash_income_amt_before_2m  double COMMENT '前一双月双月现金消耗$$单位-元', 
income_amt_before_2m  double COMMENT '前一双月双月运营消耗$$单位-元', 
imp_cnt_before_2m  bigint COMMENT '前一双月双月曝光量', 
click_cnt_before_2m  bigint COMMENT '前一双月双月点击量', 
like_cnt_before_2m  bigint COMMENT '前一双月双月点赞量', 
fav_cnt_before_2m  bigint COMMENT '前一双月双月收藏量', 
cmt_cnt_before_2m  bigint COMMENT '前一双月双月评论量', 
share_cnt_before_2m  bigint COMMENT '前一双月双月分享量', 
follow_cnt_before_2m  bigint COMMENT '前一双月双月关注量', 
screenshot_cnt_before_2m  bigint COMMENT '前一双月双月截屏数', 
engage_cnt bigint COMMENT '前一双月双月互动数', 
click_rgmv_7d_before_2m  double COMMENT '前一双月双月7天点击口径购买rgmv,单位元$$新转化表redcdm.dws_ads_cvr_creativity_before_2m_di，sum(coalesce(purchase_rgmv,0)+coalesce(mini_purchase_rgmv,0)) as click_rgmv_7d', 
conversion_cnt_before_2m  bigint COMMENT '前一双月双月转化量，即文档中线索量$$20230605及以后有数', 
ecm_unclosed_rgmv_before_2m  double COMMENT'前一双月双月非闭环电商rgmv',
rtb_cost_income_amt_before_2m  double COMMENT'前一双月双月分场域营销目的预算使用率分子',
rtb_budget_income_amt_before_2m  double COMMENT'前一双月双月分场域营销目的预算使用率分母',
cost_income_amt_before_2m  double COMMENT'前一双月双月分场域预算使用率分子',
budget_income_amt_before_2m  double COMMENT'前一双月双月分场域预算使用率分母',
advertiser_budget_income_amt_before_2m  double COMMENT'前一双月双月预算使用率分母',
advertiser_cost_income_amt_before_2m  double COMMENT'前一双月双月预算使用率分子',
cash_balance_before_2m  double COMMENT'前一双月双月余额',
  track_group_cost_income_amt double COMMENT'一级赛道分场域预算使用率分子',
  track_group_budget_income_amt double COMMENT'一级赛道分场域预算使用率分母',
  track_group_advertiser_cost_income_amt double COMMENT'一级赛道预算使用率分子',
  track_group_advertiser_budget_income_amt double COMMENT'一级赛道预算使用率分母',
  track_group_rtb_cost_income_amt double COMMENT'一级赛道分场域营销目标预算使用率分子',
  track_group_rtb_budget_income_amt double COMMENT'一级赛道分场域营销目标预算使用率分母',
  track_group_cash_income_amt_before_2m double COMMENT'一级赛道前一双月现金消耗',
  track_group_cash_income_amt_2m double COMMENT'一级赛道本双月现金消耗',
  track_group_cash_income_amt_last_2m double COMMENT'一级赛道去年双月现金消耗',
  track_cost_income_amt double COMMENT'赛道行业分场域预算使用率分子',
  track_budget_income_amt double COMMENT'赛道行业分场域预算使用率分母',
  track_advertiser_cost_income_amt double COMMENT'赛道行业预算使用率分子',
  track_advertiser_budget_income_amt double COMMENT'赛道行业预算使用率分母',
  track_rtb_cost_income_amt double COMMENT'赛道行业分场域营销目标预算使用率分子',
  track_rtb_budget_income_amt double COMMENT'赛道行业分场域营销目标预算使用率分母',
  cash_income_amt_1y double comment'本年流水',
  cash_income_amt_before_1y double comment'去年同期流水'
  )