--月力度企业号聚合
select brand_account_id,
  seller_id,
  user_name,
  shopname,
  state,
  frozen,
  seller_type,
  seller_level,
  main_category_name,
  industry,
  first_category_name,
  second_category_name,
  third_category_name,
  first_audit_time,
  create_dt,
  shop_user_type,
  deal_gmv_1m as deal_gmv,
  rtb_cash_cost_1m as rtb_cash_cost,
  brand_cash_cost_1m as brand_cash_cost,
  ti_cash_cost_1m as ti_cash_cost,
  brand_zone_cash_cost_1m as brand_zone_cash_cost,
  ecm_closed_cash_cost_1m as ecm_closed_cash_cost,
  sx_cash_cost_1m as sx_cash_cost,
  brand_ti_cost_1m as brand_ti_cost,
  brand_target_type_cost_1m as brand_target_type_cost,
  dtm,
  company_code,
  company_id,
  track_industry_name,
  process_track_industry_name,
  fans_num,
  fans_level,
  cash_cost_180d,
  ti_cash_cost_180d_type,
  account_ecm_type,
  track_industry_dept_group_name,
  company_name,
  track_group_name,
  substring(date_key,1,6) as stat_month,
  account_type,
  date_key

from bi_ads.app_ads_industry_account_seller_30d_df
where dtm=(select max(dtm) from bi_ads.app_ads_industry_account_seller_30d_df)
