SELECT coalesce(`a`.`date_key`,
date_format(`c`.`dtm`,
    'yyyy-MM-dd')) AS `date_key`,
`a`.`module`,
`a`.`product`,
coalesce(`a`.`brand_account_id`,
    `c`.`brand_account_id`) AS `brand_account_id`,
`b`.`brand_user_name`,
`b`.`company_code`,
`b`.`company_name`,
`b`.`group_code`,
`b`.`group_name`,
`b`.`trade_type_first_name`,
`b`.`trade_type_second_name`,
`b`.`track_group_id`,
`b`.`track_group_name`,
`b`.`track_industry_name`,
`b`.`track_detail_name`,
CASE WHEN (`b`.`active_level` = '其他客户') THEN '持续沉睡客户' ELSE `b`.`active_level` END AS `active_level`,
CASE WHEN ((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept1_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept1_name` END AS `direct_sales_dept1_name`,
CASE WHEN ((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept2_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept2_name` END AS `direct_sales_dept2_name`,
CASE WHEN ((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept3_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept3_name` END AS `direct_sales_dept3_name`,
CASE WHEN ((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept4_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept4_name` END AS `direct_sales_dept4_name`,
CASE WHEN ((((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) AND (`b`.`cpc_direct_sales_dept4_name` LIKE '%美妆%')) AND (`b`.`cpc_direct_sales_dept3_name` = '美奢洗护行业')) THEN '美妆洗护行业' WHEN (((`a`.`module` IN ('效果',
'薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) AND (`b`.`cpc_direct_sales_dept4_name` = '奢品行业部门')) THEN '奢品行业' WHEN ((`a`.`module` IN ('效果',
'薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept4_name` WHEN (((`a`.`module` IN ('品牌',
    'IP')) AND (`b`.`brand_direct_sales_dept4_name` LIKE '%美妆%')) AND (`b`.`brand_direct_sales_dept3_name` = '美奢洗护行业')) THEN '美妆洗护行业' WHEN ((`a`.`module` IN ('品牌',
'IP')) AND (`b`.`brand_direct_sales_dept4_name` = '奢品行业部门')) THEN '奢品行业' WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept4_name` END AS `direct_sales_dept4_all_name`,
CASE WHEN ((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept5_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept5_name` END AS `direct_sales_dept5_name`,
CASE WHEN (((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) AND ((`b`.`cpc_direct_sales_dept4_name` = '奢品行业部门') OR (`b`.`cpc_direct_sales_dept3_name` = '本地客户业务部'))) THEN `b`.`cpc_direct_sales_dept5_name` WHEN ((`a`.`module` IN ('效果',
'薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept4_name` WHEN ((`a`.`module` IN ('品牌',
'IP')) AND ((`b`.`brand_direct_sales_dept4_name` = '奢品行业部门') OR (`b`.`brand_direct_sales_dept3_name` = '本地客户业务部'))) THEN `b`.`brand_direct_sales_dept5_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept4_name` END AS `direct_sales_dept5_all_name`,
CASE WHEN ((`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) OR (`a`.`module` IS NULL)) THEN `b`.`cpc_direct_sales_dept6_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_dept6_name` END AS `direct_sales_dept6_name`,
`b`.`brand_tag_code`,
`b`.`brand_tag_name`,
`b`.`brand_group_tag_code`,
`b`.`brand_group_tag_name`,
`b`.`cpc_direct_sales_code`,
`b`.`cpc_direct_sales_name`,
`b`.`cpc_direct_sales_dept1_code`,
`b`.`cpc_direct_sales_dept1_name`,
`b`.`cpc_direct_sales_dept2_code`,
`b`.`cpc_direct_sales_dept2_name`,
`b`.`cpc_direct_sales_dept3_code`,
`b`.`cpc_direct_sales_dept3_name`,
`b`.`cpc_direct_sales_dept4_code`,
`b`.`cpc_direct_sales_dept4_name`,
`b`.`cpc_direct_sales_dept5_code`,
`b`.`cpc_direct_sales_dept5_name`,
`b`.`cpc_direct_sales_dept6_code`,
`b`.`cpc_direct_sales_dept6_name`,
`b`.`brand_direct_sales_code`,
`b`.`brand_direct_sales_name`,
`b`.`brand_direct_sales_dept1_code`,
`b`.`brand_direct_sales_dept1_name`,
`b`.`brand_direct_sales_dept2_code`,
`b`.`brand_direct_sales_dept2_name`,
`b`.`brand_direct_sales_dept3_code`,
`b`.`brand_direct_sales_dept3_name`,
`b`.`brand_direct_sales_dept4_code`,
`b`.`brand_direct_sales_dept4_name`,
`b`.`brand_direct_sales_dept5_code`,
`b`.`brand_direct_sales_dept5_name`,
`b`.`brand_direct_sales_dept6_code`,
`b`.`brand_direct_sales_dept6_name`,
`b`.`chips_direct_operator_code`,
`b`.`chips_direct_operator_name`,
`b`.`chips_direct_operator_dept1_code`,
`b`.`chips_direct_operator_dept1_name`,
`b`.`chips_direct_operator_dept2_code`,
`b`.`chips_direct_operator_dept2_name`,
`b`.`chips_direct_operator_dept3_code`,
`b`.`chips_direct_operator_dept3_name`,
`b`.`chips_direct_operator_dept4_code`,
`b`.`chips_direct_operator_dept4_name`,
`b`.`chips_direct_operator_dept5_code`,
`b`.`chips_direct_operator_dept5_name`,
`b`.`chips_direct_operator_dept6_code`,
`b`.`chips_direct_operator_dept6_name`,
`b`.`bcoo_direct_sales_code`,
`b`.`bcoo_direct_sales_name`,
`b`.`bcoo_direct_sales_dept1_code`,
`b`.`bcoo_direct_sales_dept1_name`,
`b`.`bcoo_direct_sales_dept2_code`,
`b`.`bcoo_direct_sales_dept2_name`,
`b`.`bcoo_direct_sales_dept3_code`,
`b`.`bcoo_direct_sales_dept3_name`,
`b`.`bcoo_direct_sales_dept4_code`,
`b`.`bcoo_direct_sales_dept4_name`,
`b`.`bcoo_direct_sales_dept5_code`,
`b`.`bcoo_direct_sales_dept5_name`,
`b`.`bcoo_direct_sales_dept6_code`,
`b`.`bcoo_direct_sales_dept6_name`,
`a`.`imp_cnt`,
`a`.`click_cnt`,
`a`.`like_cnt`,
`a`.`fav_cnt`,
`a`.`cmt_cnt`,
`a`.`share_cnt`,
`a`.`follow_cnt`,
`a`.`cash_cost`,
`a`.`cost`,
`a`.`mkt_ecm_cost`,
`a`.`mkt_leads_cost`,
`a`.`mkt_zc_cost`,
`a`.`open_sale_num`,
`a`.`direct_cash_cost`,
`a`.`direct_cost`,
`a`.`channel_cash_cost`,
`a`.`channel_cost`,
`a`.`campaign_cnt`,
`a`.`unit_cnt`,
`a`.`brand_campaign_cnt`,
`a`.`cpc_cost_budget_rate`,
`a`.`cpc_budget`,
`a`.`dtm` AS `metric_dtm`,
`c`.`dtm` AS `dim_dtm`,
`b`.`first_industry_name`,
`b`.`second_industry_name`,
`a`.`market_target`,
`b`.`cpc_operator_code`,
`b`.`cpc_operator_name`,
`b`.`cpc_operator_dept1_code`,
`b`.`cpc_operator_dept1_name`,
`b`.`cpc_operator_dept2_code`,
`b`.`cpc_operator_dept2_name`,
`b`.`cpc_operator_dept3_code`,
`b`.`cpc_operator_dept3_name`,
`b`.`cpc_operator_dept4_code`,
CASE WHEN (`b`.`cpc_operator_dept4_name` LIKE '%美妆%') THEN '美妆洗护行业' WHEN (`b`.`cpc_operator_dept4_name` = '奢品行业部门') THEN '奢品行业' ELSE `b`.`cpc_operator_dept4_name` END AS `cpc_operator_dept4_name`,
`b`.`cpc_operator_dept5_code`,
CASE WHEN (`b`.`cpc_operator_dept4_name` LIKE '%美妆%') THEN `b`.`cpc_operator_dept4_name` ELSE `b`.`cpc_operator_dept5_name` END AS `cpc_operator_dept5_name`,
`b`.`cpc_operator_dept6_code`,
`b`.`cpc_operator_dept6_name`,
CASE WHEN (`a`.`module` IN ('效果',
    '薯条',
'品合',
'内容加热')) THEN `b`.`cpc_direct_sales_name` WHEN (`a`.`module` IN ('品牌',
'IP')) THEN `b`.`brand_direct_sales_name` END AS `direct_sales_name`,
`c`.`ads_last_cost_days`,
`c`.`bimonthly_last_brand_active_level`,
`c`.`brand_active_level`,
`c`.`ads_last_cost_date`,
substr(`b`.`brand_account_create_time`,
    1,
10) AS `brand_account_create_date`
FROM redcdm.dm_ads_industry_product_account_td_df AS `a` 
FULL OUTER JOIN 
(SELECT `brand_account_id`,
    `dtm`,
`ads_last_cost_days`,
`bimonthly_last_brand_active_level`,
`brand_active_level`,
`ads_last_cost_date`
FROM redcdm.dim_ads_industry_account_df) c 
ON `a`.`brand_account_id` = `c`.`brand_account_id` 
LEFT OUTER JOIN 
(SELECT `brand_account_id`,
`brand_user_name`,
`company_code`,
`company_name`,
`group_code`,
`group_name`,
`trade_type_first_name`,
`trade_type_second_name`,
`track_group_id`,
`track_group_name`,
`active_level`,
`cpc_direct_sales_code`,
`cpc_direct_sales_name`,
`cpc_direct_sales_dept1_code`,
`cpc_direct_sales_dept1_name`,
`cpc_direct_sales_dept2_code`,
`cpc_direct_sales_dept2_name`,
`cpc_direct_sales_dept3_code`,
`cpc_direct_sales_dept3_name`,
`cpc_direct_sales_dept4_code`,
`cpc_direct_sales_dept4_name`,
`cpc_direct_sales_dept5_code`,
`cpc_direct_sales_dept5_name`,
`cpc_direct_sales_dept6_code`,
`cpc_direct_sales_dept6_name`,
`brand_direct_sales_code`,
`brand_direct_sales_name`,
`brand_direct_sales_dept1_code`,
`brand_direct_sales_dept1_name`,
`brand_direct_sales_dept2_code`,
`brand_direct_sales_dept2_name`,
`brand_direct_sales_dept3_code`,
`brand_direct_sales_dept3_name`,
`brand_direct_sales_dept4_code`,
`brand_direct_sales_dept4_name`,
`brand_direct_sales_dept5_code`,
`brand_direct_sales_dept5_name`,
`brand_direct_sales_dept6_code`,
`brand_direct_sales_dept6_name`,
`chips_direct_operator_code`,
`chips_direct_operator_name`,
`chips_direct_operator_dept1_code`,
`chips_direct_operator_dept1_name`,
`chips_direct_operator_dept2_code`,
`chips_direct_operator_dept2_name`,
`chips_direct_operator_dept3_code`,
`chips_direct_operator_dept3_name`,
`chips_direct_operator_dept4_code`,
`chips_direct_operator_dept4_name`,
`chips_direct_operator_dept5_code`,
`chips_direct_operator_dept5_name`,
`chips_direct_operator_dept6_code`,
`chips_direct_operator_dept6_name`,
`bcoo_direct_sales_code`,
`bcoo_direct_sales_name`,
`bcoo_direct_sales_dept1_code`,
`bcoo_direct_sales_dept1_name`,
`bcoo_direct_sales_dept2_code`,
`bcoo_direct_sales_dept2_name`,
`bcoo_direct_sales_dept3_code`,
`bcoo_direct_sales_dept3_name`,
`bcoo_direct_sales_dept4_code`,
`bcoo_direct_sales_dept4_name`,
`bcoo_direct_sales_dept5_code`,
`bcoo_direct_sales_dept5_name`,
`bcoo_direct_sales_dept6_code`,
`bcoo_direct_sales_dept6_name`,
`dtm`,
`brand_tag_code`,
`brand_tag_name`,
`brand_group_tag_code`,
`brand_group_tag_name`,
`first_industry_name`,
`second_industry_name`,
`track_detail_name`,
`track_industry_name`,
`cpc_operator_code`,
`cpc_operator_name`,
`cpc_operator_dept1_code`,
`cpc_operator_dept1_name`,
`cpc_operator_dept2_code`,
`cpc_operator_dept2_name`,
`cpc_operator_dept3_code`,
`cpc_operator_dept3_name`,
`cpc_operator_dept4_code`,
`cpc_operator_dept4_name`,
`cpc_operator_dept5_code`,
`cpc_operator_dept5_name`,
`cpc_operator_dept6_code`,
`cpc_operator_dept6_name`,
`brand_active_level`,
`ads_last_cost_days`,
`bimonthly_last_brand_active_level`,
`ads_last_cost_date`,
`brand_account_create_time`,
`brand_account_create_date`,
`direct_sales_dept3_name`,
`direct_sales_dept4_all_name`,
`direct_sales_dept5_all_name`
FROM redcdm.dim_ads_industry_account_df
WHERE (date(`dtm`)) = (from_unixtime(((unix_timestamp(now())) - 86400) - 25200,
    '%Y-%m-%d'))
) b ON (coalesce(`a`.`brand_account_id`,
`c`.`brand_account_id`)) = `b`.`brand_account_id`;


