CREATE VIEW `app_ads_industry_product_account_td_df_view` (date_key,
  module,
product,
brand_account_id,
brand_user_name,
company_code,
company_name,
group_code,
group_name,
trade_type_first_name,
trade_type_second_name,
track_group_id,
track_group_name,
track_industry_name,
track_detail_name,
active_level,
direct_sales_dept1_name,
direct_sales_dept2_name,
direct_sales_dept3_name,
direct_sales_dept4_name,
direct_sales_dept4_all_name,
direct_sales_dept5_name,
direct_sales_dept5_all_name,
direct_sales_dept6_name,
brand_tag_code,
brand_tag_name,
brand_group_tag_code,
brand_group_tag_name,
cpc_direct_sales_code,
cpc_direct_sales_name,
cpc_direct_sales_dept1_code,
cpc_direct_sales_dept1_name,
cpc_direct_sales_dept2_code,
cpc_direct_sales_dept2_name,
cpc_direct_sales_dept3_code,
cpc_direct_sales_dept3_name,
cpc_direct_sales_dept4_code,
cpc_direct_sales_dept4_name,
cpc_direct_sales_dept5_code,
cpc_direct_sales_dept5_name,
cpc_direct_sales_dept6_code,
cpc_direct_sales_dept6_name,
brand_direct_sales_code,
brand_direct_sales_name,
brand_direct_sales_dept1_code,
brand_direct_sales_dept1_name,
brand_direct_sales_dept2_code,
brand_direct_sales_dept2_name,
brand_direct_sales_dept3_code,
brand_direct_sales_dept3_name,
brand_direct_sales_dept4_code,
brand_direct_sales_dept4_name,
brand_direct_sales_dept5_code,
brand_direct_sales_dept5_name,
brand_direct_sales_dept6_code,
brand_direct_sales_dept6_name,
chips_direct_operator_code,
chips_direct_operator_name,
chips_direct_operator_dept1_code,
chips_direct_operator_dept1_name,
chips_direct_operator_dept2_code,
chips_direct_operator_dept2_name,
chips_direct_operator_dept3_code,
chips_direct_operator_dept3_name,
chips_direct_operator_dept4_code,
chips_direct_operator_dept4_name,
chips_direct_operator_dept5_code,
chips_direct_operator_dept5_name,
chips_direct_operator_dept6_code,
chips_direct_operator_dept6_name,
bcoo_direct_sales_code,
bcoo_direct_sales_name,
bcoo_direct_sales_dept1_code,
bcoo_direct_sales_dept1_name,
bcoo_direct_sales_dept2_code,
bcoo_direct_sales_dept2_name,
bcoo_direct_sales_dept3_code,
bcoo_direct_sales_dept3_name,
bcoo_direct_sales_dept4_code,
bcoo_direct_sales_dept4_name,
bcoo_direct_sales_dept5_code,
bcoo_direct_sales_dept5_name,
bcoo_direct_sales_dept6_code,
bcoo_direct_sales_dept6_name,
imp_cnt,
click_cnt,
like_cnt,
fav_cnt,
cmt_cnt,
share_cnt,
follow_cnt,
cash_cost,
cost,
mkt_ecm_cost,
mkt_leads_cost,
mkt_zc_cost,
open_sale_num,
direct_cash_cost,
direct_cost,
channel_cash_cost,
channel_cost,
campaign_cnt,
unit_cnt,
brand_campaign_cnt,
cpc_cost_budget_rate,
cpc_budget,
metric_dtm,
dim_dtm,
first_industry_name,
second_industry_name,
market_target,
cpc_operator_code,
cpc_operator_name,
cpc_operator_dept1_code,
cpc_operator_dept1_name,
cpc_operator_dept2_code,
cpc_operator_dept2_name,
cpc_operator_dept3_code,
cpc_operator_dept3_name,
cpc_operator_dept4_code,
cpc_operator_dept4_name,
cpc_operator_dept5_code,
cpc_operator_dept5_name,
cpc_operator_dept6_code,
cpc_operator_dept6_name,
direct_sales_name,
ads_last_cost_days,
bimonthly_last_brand_active_level,
brand_active_level,
ads_last_cost_date,
brand_account_create_date) COMMENT "VIEW" AS SELECT coalesce(`reddm`.`a`.`date_key`,
date_format(`reddm`.`b`.`dtm`,
  'yyyy-MM-dd')) AS `date_key`,
`reddm`.`a`.`module`,
`reddm`.`a`.`product`,
coalesce(`reddm`.`a`.`brand_account_id`,
  `reddm`.`b`.`brand_account_id`) AS `brand_account_id`,
`reddm`.`b`.`brand_user_name`,
`reddm`.`b`.`company_code`,
`reddm`.`b`.`company_name`,
`reddm`.`b`.`group_code`,
`reddm`.`b`.`group_name`,
`reddm`.`b`.`trade_type_first_name`,
`reddm`.`b`.`trade_type_second_name`,
`reddm`.`b`.`track_group_id`,
`reddm`.`b`.`track_group_name`,
`reddm`.`b`.`track_industry_name`,
`reddm`.`b`.`track_detail_name`,
CASE WHEN (`reddm`.`b`.`active_level` = '其他客户') THEN '持续沉睡客户' ELSE `reddm`.`b`.`active_level` END AS `active_level`,
CASE WHEN ((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept1_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept1_name` END AS `direct_sales_dept1_name`,
CASE WHEN ((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept2_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept2_name` END AS `direct_sales_dept2_name`,
CASE WHEN ((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept3_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept3_name` END AS `direct_sales_dept3_name`,
CASE WHEN ((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept4_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept4_name` END AS `direct_sales_dept4_name`,
CASE WHEN ((((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) AND (`reddm`.`b`.`cpc_direct_sales_dept4_name` LIKE '%美妆%')) AND (`reddm`.`b`.`cpc_direct_sales_dept3_name` = '美奢洗护行业')) THEN '美妆洗护行业' WHEN (((`reddm`.`a`.`module` IN ('效果',
'薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) AND (`reddm`.`b`.`cpc_direct_sales_dept4_name` = '奢品行业部门')) THEN '奢品行业' WHEN ((`reddm`.`a`.`module` IN ('效果',
'薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept4_name` WHEN (((`reddm`.`a`.`module` IN ('品牌',
  'IP')) AND (`reddm`.`b`.`brand_direct_sales_dept4_name` LIKE '%美妆%')) AND (`reddm`.`b`.`brand_direct_sales_dept3_name` = '美奢洗护行业')) THEN '美妆洗护行业' WHEN ((`reddm`.`a`.`module` IN ('品牌',
'IP')) AND (`reddm`.`b`.`brand_direct_sales_dept4_name` = '奢品行业部门')) THEN '奢品行业' WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept4_name` END AS `direct_sales_dept4_all_name`,
CASE WHEN ((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept5_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept5_name` END AS `direct_sales_dept5_name`,
CASE WHEN (((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) AND ((`reddm`.`b`.`cpc_direct_sales_dept4_name` = '奢品行业部门') OR (`reddm`.`b`.`cpc_direct_sales_dept3_name` = '本地客户业务部'))) THEN `reddm`.`b`.`cpc_direct_sales_dept5_name` WHEN ((`reddm`.`a`.`module` IN ('效果',
'薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept4_name` WHEN ((`reddm`.`a`.`module` IN ('品牌',
'IP')) AND ((`reddm`.`b`.`brand_direct_sales_dept4_name` = '奢品行业部门') OR (`reddm`.`b`.`brand_direct_sales_dept3_name` = '本地客户业务部'))) THEN `reddm`.`b`.`brand_direct_sales_dept5_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept4_name` END AS `direct_sales_dept5_all_name`,
CASE WHEN ((`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) OR (`reddm`.`a`.`module` IS NULL)) THEN `reddm`.`b`.`cpc_direct_sales_dept6_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_dept6_name` END AS `direct_sales_dept6_name`,
`reddm`.`b`.`brand_tag_code`,
`reddm`.`b`.`brand_tag_name`,
`reddm`.`b`.`brand_group_tag_code`,
`reddm`.`b`.`brand_group_tag_name`,
`reddm`.`b`.`cpc_direct_sales_code`,
`reddm`.`b`.`cpc_direct_sales_name`,
`reddm`.`b`.`cpc_direct_sales_dept1_code`,
`reddm`.`b`.`cpc_direct_sales_dept1_name`,
`reddm`.`b`.`cpc_direct_sales_dept2_code`,
`reddm`.`b`.`cpc_direct_sales_dept2_name`,
`reddm`.`b`.`cpc_direct_sales_dept3_code`,
`reddm`.`b`.`cpc_direct_sales_dept3_name`,
`reddm`.`b`.`cpc_direct_sales_dept4_code`,
`reddm`.`b`.`cpc_direct_sales_dept4_name`,
`reddm`.`b`.`cpc_direct_sales_dept5_code`,
`reddm`.`b`.`cpc_direct_sales_dept5_name`,
`reddm`.`b`.`cpc_direct_sales_dept6_code`,
`reddm`.`b`.`cpc_direct_sales_dept6_name`,
`reddm`.`b`.`brand_direct_sales_code`,
`reddm`.`b`.`brand_direct_sales_name`,
`reddm`.`b`.`brand_direct_sales_dept1_code`,
`reddm`.`b`.`brand_direct_sales_dept1_name`,
`reddm`.`b`.`brand_direct_sales_dept2_code`,
`reddm`.`b`.`brand_direct_sales_dept2_name`,
`reddm`.`b`.`brand_direct_sales_dept3_code`,
`reddm`.`b`.`brand_direct_sales_dept3_name`,
`reddm`.`b`.`brand_direct_sales_dept4_code`,
`reddm`.`b`.`brand_direct_sales_dept4_name`,
`reddm`.`b`.`brand_direct_sales_dept5_code`,
`reddm`.`b`.`brand_direct_sales_dept5_name`,
`reddm`.`b`.`brand_direct_sales_dept6_code`,
`reddm`.`b`.`brand_direct_sales_dept6_name`,
`reddm`.`b`.`chips_direct_operator_code`,
`reddm`.`b`.`chips_direct_operator_name`,
`reddm`.`b`.`chips_direct_operator_dept1_code`,
`reddm`.`b`.`chips_direct_operator_dept1_name`,
`reddm`.`b`.`chips_direct_operator_dept2_code`,
`reddm`.`b`.`chips_direct_operator_dept2_name`,
`reddm`.`b`.`chips_direct_operator_dept3_code`,
`reddm`.`b`.`chips_direct_operator_dept3_name`,
`reddm`.`b`.`chips_direct_operator_dept4_code`,
`reddm`.`b`.`chips_direct_operator_dept4_name`,
`reddm`.`b`.`chips_direct_operator_dept5_code`,
`reddm`.`b`.`chips_direct_operator_dept5_name`,
`reddm`.`b`.`chips_direct_operator_dept6_code`,
`reddm`.`b`.`chips_direct_operator_dept6_name`,
`reddm`.`b`.`bcoo_direct_sales_code`,
`reddm`.`b`.`bcoo_direct_sales_name`,
`reddm`.`b`.`bcoo_direct_sales_dept1_code`,
`reddm`.`b`.`bcoo_direct_sales_dept1_name`,
`reddm`.`b`.`bcoo_direct_sales_dept2_code`,
`reddm`.`b`.`bcoo_direct_sales_dept2_name`,
`reddm`.`b`.`bcoo_direct_sales_dept3_code`,
`reddm`.`b`.`bcoo_direct_sales_dept3_name`,
`reddm`.`b`.`bcoo_direct_sales_dept4_code`,
`reddm`.`b`.`bcoo_direct_sales_dept4_name`,
`reddm`.`b`.`bcoo_direct_sales_dept5_code`,
`reddm`.`b`.`bcoo_direct_sales_dept5_name`,
`reddm`.`b`.`bcoo_direct_sales_dept6_code`,
`reddm`.`b`.`bcoo_direct_sales_dept6_name`,
`reddm`.`a`.`imp_cnt`,
`reddm`.`a`.`click_cnt`,
`reddm`.`a`.`like_cnt`,
`reddm`.`a`.`fav_cnt`,
`reddm`.`a`.`cmt_cnt`,
`reddm`.`a`.`share_cnt`,
`reddm`.`a`.`follow_cnt`,
`reddm`.`a`.`cash_cost`,
`reddm`.`a`.`cost`,
`reddm`.`a`.`mkt_ecm_cost`,
`reddm`.`a`.`mkt_leads_cost`,
`reddm`.`a`.`mkt_zc_cost`,
`reddm`.`a`.`open_sale_num`,
`reddm`.`a`.`direct_cash_cost`,
`reddm`.`a`.`direct_cost`,
`reddm`.`a`.`channel_cash_cost`,
`reddm`.`a`.`channel_cost`,
`reddm`.`a`.`campaign_cnt`,
`reddm`.`a`.`unit_cnt`,
`reddm`.`a`.`brand_campaign_cnt`,
`reddm`.`a`.`cpc_cost_budget_rate`,
`reddm`.`a`.`cpc_budget`,
`reddm`.`a`.`dtm` AS `metric_dtm`,
`reddm`.`b`.`dtm` AS `dim_dtm`,
`reddm`.`b`.`first_industry_name`,
`reddm`.`b`.`second_industry_name`,
`reddm`.`a`.`market_target`,
`reddm`.`b`.`cpc_operator_code`,
`reddm`.`b`.`cpc_operator_name`,
`reddm`.`b`.`cpc_operator_dept1_code`,
`reddm`.`b`.`cpc_operator_dept1_name`,
`reddm`.`b`.`cpc_operator_dept2_code`,
`reddm`.`b`.`cpc_operator_dept2_name`,
`reddm`.`b`.`cpc_operator_dept3_code`,
`reddm`.`b`.`cpc_operator_dept3_name`,
`reddm`.`b`.`cpc_operator_dept4_code`,
CASE WHEN (`reddm`.`b`.`cpc_operator_dept4_name` LIKE '%美妆%') THEN '美妆洗护行业' WHEN (`reddm`.`b`.`cpc_operator_dept4_name` = '奢品行业部门') THEN '奢品行业' ELSE `reddm`.`b`.`cpc_operator_dept4_name` END AS `cpc_operator_dept4_name`,
`reddm`.`b`.`cpc_operator_dept5_code`,
CASE WHEN (`reddm`.`b`.`cpc_operator_dept4_name` LIKE '%美妆%') THEN `reddm`.`b`.`cpc_operator_dept4_name` ELSE `reddm`.`b`.`cpc_operator_dept5_name` END AS `cpc_operator_dept5_name`,
`reddm`.`b`.`cpc_operator_dept6_code`,
`reddm`.`b`.`cpc_operator_dept6_name`,
CASE WHEN (`reddm`.`a`.`module` IN ('效果',
  '薯条',
'品合',
'内容加热')) THEN `reddm`.`b`.`cpc_direct_sales_name` WHEN (`reddm`.`a`.`module` IN ('品牌',
'IP')) THEN `reddm`.`b`.`brand_direct_sales_name` END AS `direct_sales_name`,
`reddm`.`b`.`ads_last_cost_days`,
`reddm`.`b`.`bimonthly_last_brand_active_level`,
`reddm`.`b`.`brand_active_level`,
`reddm`.`b`.`ads_last_cost_date`,
substr(`reddm`.`b`.`brand_account_create_time`,
  1,
10) AS `brand_account_create_date`
FROM `reddm`.`dm_ads_industry_product_account_td_df` AS `a` LEFT OUTER JOIN `reddm`.`dim_ads_industry_account_df` AS `b` ON `reddm`.`a`.`brand_account_id` = `reddm`.`b`.`brand_account_id`;