select 
  virtual_seller_id,
  product,
  market_target_type,
  virtual_seller_name,
  advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  direct_sales_dept3_name,
  direct_sales_dept4_name,
  direct_sales_dept5_name,
  direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  direct_sales_name,
  cpc_operator_name,
  cost_1h,
  ystd_cost_1h,
  cost_1d,
  ystd_cost_1d,
  total_balance,
  budget_amt,
  dtm,
  hh,
  ystd_budget_amt,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  ystd_total_balance_1d,
  total_balance_before_1d,
  budget_amt_before_1d,
  track_budget_amt,
  track_cost_1d,
  track_group_budget_amt,
  track_group_cost_1d,
  valid_campaign_cnt,
  campaign_day_budget_income_amt,
  limit_day_budget,
  ystd_imp_cnt_1d,
  ystd_click_cnt_1d,
  before_imp_cnt_1d,
  before_click_cnt_1d,
  before_cost_1d,
  imp_cnt_1d,
  click_cnt_1d,
  rgmv_1d,
  purchase_order_gmv_7d_1d,
  out_click_rgmv_7d_1d,
  engage_cnt_1d,
  ystd_rgmv_1d,
  ystd_purchase_order_gmv_7d_1d,
  ystd_out_click_rgmv_7d_1d,
  ystd_engage_cnt_1d,
  before_rgmv_1d,
  before_purchase_order_gmv_7d_1d,
  before_out_click_rgmv_7d_1d,
  before_engage_cnt_1d,
  case when maxhh.max_hh is not null then 1 else 0 end as max_hh
from 
(
  SELECT
 virtual_seller_id,
  product,
  market_target_type,
  virtual_seller_name,
  advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  direct_sales_dept3_name,
  direct_sales_dept4_name,
  direct_sales_dept5_name,
  direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  direct_sales_name,
  cpc_operator_name,
  cost_1h,
  ystd_cost_1h,
  cost_1d,
  ystd_cost_1d,
  total_balance,
  budget_amt,
  cast(dtm as int) as dtm,
  hh,
  ystd_budget_amt,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  ystd_total_balance_1d,
  total_balance_before_1d,
  budget_amt_before_1d,
  track_budget_amt,
  track_cost_1d,
  track_group_budget_amt,
  track_group_cost_1d,
  valid_campaign_cnt,
  campaign_budget_income_amt as campaign_day_budget_income_amt,
  limit_day_budget,
  ystd_imp_cnt_1d,
  ystd_click_cnt_1d,
  before_imp_cnt_1d,
  before_click_cnt_1d,
  before_cost_1d,
  imp_cnt_1d,
  click_cnt_1d,
  rgmv_1d,
  purchase_order_gmv_7d_1d,
  out_click_rgmv_7d_1d,
  engage_cnt_1d,
  ystd_rgmv_1d,
  ystd_purchase_order_gmv_7d_1d,
  ystd_out_click_rgmv_7d_1d,
  ystd_engage_cnt_1d,
  before_rgmv_1d,
  before_purchase_order_gmv_7d_1d,
  before_out_click_rgmv_7d_1d,
  before_engage_cnt_1d
FROM
  redcdm.dm_ads_rtb_advertiser_metric_hi
WHERE
  dtm = '{{ds_nodash}}' 
  and hh<=substring(from_unixtime(unix_timestamp(current_timestamp)+3600*7),12,2)
  and hh>='00'
  union all 
SELECT
  virtual_seller_id,
  product,
  market_target_type,
  virtual_seller_name,
  advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  direct_sales_dept3_name,
  direct_sales_dept4_name,
  direct_sales_dept5_name,
  direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  direct_sales_name,
  cpc_operator_name,
  0 as cost_1h,
  cost_1h as ystd_cost_1h,
  0 as cost_1d,
  cost_1d as ystd_cost_1d,
  0 as total_balance,
  0 as budget_amt,
  cast( '{{ds_nodash}}'  as int) as dtm,
  hh,
  budget_amt as ystd_budget_amt,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  total_balance as ystd_total_balance_1d,
  0 as total_balance_before_1d,
  0 as budget_amt_before_1d,
  0 as track_budget_amt,
  0 as track_cost_1d,
  0 as track_group_budget_amt,
  0 as track_group_cost_1d,
  0 as valid_campaign_cnt,
  0 as campaign_day_budget_income_amt,
  limit_day_budget,
  imp_cnt_1d as ystd_imp_cnt_1d,
  click_cnt_1d as ystd_click_cnt_1d,
  0 as before_imp_cnt_1d,
  0 as before_click_cnt_1d,
  0 as before_cost_1d,
  0 as imp_cnt_1d,
  0 as click_cnt_1d,
  0 as rgmv_1d,
  0 as purchase_order_gmv_7d_1d,
  0 as out_click_rgmv_7d_1d,
  0 as engage_cnt_1d,
  rgmv_1d as ystd_rgmv_1d,
  purchase_order_gmv_7d_1d as ystd_purchase_order_gmv_7d_1d,
  out_click_rgmv_7d_1d as ystd_out_click_rgmv_7d_1d,
  engage_cnt_1d as ystd_engage_cnt_1d,
  0 as before_rgmv_1d,
  0 as before_purchase_order_gmv_7d_1d,
  0 as before_out_click_rgmv_7d_1d,
  0 as before_engage_cnt_1d
FROM
  redcdm.dm_ads_rtb_advertiser_metric_hi
WHERE
  dtm =  '{{ds_1_days_ago_nodash}}'
  and hh>(select max(hh) from redcdm.dm_ads_rtb_advertiser_metric_hi where dtm = '{{ds_nodash}}' )
  and hh<='23'
  )info 
 left join 
 (select max(hh) as max_hh
  from redcdm.dm_ads_rtb_advertiser_metric_hi where dtm = '{{ds_nodash}}'
  )maxhh 
 on maxhh.max_hh = info.hh
  group by virtual_seller_id,
  product,
  market_target_type,
  virtual_seller_name,
  advertiser_id,
  brand_account_id,
  brand_user_name,
  brand_tag_code,
  brand_tag_name,
  company_code,
  company_name,
  agent_user_id,
  agent_user_name,
  agent_company_code,
  agent_company_name,
  first_industry_name,
  second_industry_name,
  track_group_id,
  track_group_name,
  track_industry_name,
  track_detail_name,
  direct_sales_dept3_name,
  direct_sales_dept4_name,
  direct_sales_dept5_name,
  direct_sales_dept6_name,
  brand_group_tag_code,
  brand_group_tag_name,
  direct_sales_name,
  cpc_operator_name,
  cost_1h,
  ystd_cost_1h,
  cost_1d,
  ystd_cost_1d,
  total_balance,
  budget_amt,
  dtm,
  hh,
  ystd_budget_amt,
  process_track_industry_name,
  process_track_group_name,
  process_track_second_name,
  process_track_third_name,
  ystd_total_balance_1d,
  total_balance_before_1d,
  budget_amt_before_1d,
  track_budget_amt,
  track_cost_1d,
  track_group_budget_amt,
  track_group_cost_1d,
  valid_campaign_cnt,
  campaign_day_budget_income_amt,
  limit_day_budget,
  ystd_imp_cnt_1d,
  ystd_click_cnt_1d,
  before_imp_cnt_1d,
  before_click_cnt_1d,
  before_cost_1d,
  imp_cnt_1d,
  click_cnt_1d,
  rgmv_1d,
  purchase_order_gmv_7d_1d,
  out_click_rgmv_7d_1d,
  engage_cnt_1d,
  ystd_rgmv_1d,
  ystd_purchase_order_gmv_7d_1d,
  ystd_out_click_rgmv_7d_1d,
  ystd_engage_cnt_1d,
  before_rgmv_1d,
  before_purchase_order_gmv_7d_1d,
  before_out_click_rgmv_7d_1d,
  before_engage_cnt_1d,
  case when maxhh.max_hh is not null then 1 else 0 end
